/** Query key families. Invalidate by prefix: `queryClient.invalidateQueries({ queryKey: keys.sessions.all })`. */
export const keys = {
  bootstrap: ['bootstrap'] as const,
  auth: ['auth'] as const,
  settings: ['settings'] as const,
  profiles: ['profiles'] as const,
  activeProfile: ['profile', 'active'] as const,
  models: ['models'] as const,
  providers: ['providers'] as const,
  providerQuotas: ['providers', 'quotas'] as const,
  personalities: ['personalities'] as const,
  auxiliaryModels: ['models', 'auxiliary'] as const,
  sessions: {
    all: ['sessions'] as const,
    list: (params: Record<string, string | boolean | number | undefined>) => ['sessions', 'list', params] as const,
    detail: (id: string) => ['sessions', 'detail', id] as const,
    status: (id: string) => ['sessions', 'status', id] as const,
    usage: (id: string) => ['sessions', 'usage', id] as const,
    search: (q: string) => ['sessions', 'search', q] as const,
  },
  projects: ['projects'] as const,
  prompts: ['prompts'] as const,
  commands: ['commands'] as const,
  workspaces: ['workspaces'] as const,
  files: {
    list: (workspace: string, path: string, hidden: boolean) => ['files', 'list', workspace, path, hidden] as const,
    content: (workspace: string, path: string) => ['files', 'content', workspace, path] as const,
    git: (workspace: string) => ['files', 'git', workspace] as const,
  },
  skills: { all: ['skills'] as const, content: (name: string) => ['skills', 'content', name] as const, usage: ['skills', 'usage'] as const },
  memory: ['memory'] as const,
  crons: { all: ['crons'] as const, list: (allProfiles: boolean) => ['crons', 'list', allProfiles] as const, status: ['crons', 'status'] as const, history: (id: string) => ['crons', 'history', id] as const, run: (id: string, filename: string) => ['crons', 'history', id, filename] as const, output: (id: string) => ['crons', 'output', id] as const, deliveryOptions: ['crons', 'delivery-options'] as const },
  kanban: { boards: ['kanban', 'boards'] as const, board: (slug: string | undefined) => ['kanban', 'board', slug ?? ''] as const },
  insights: (days: number) => ['insights', days] as const,
  logs: (file: string, tail: number) => ['logs', file, tail] as const,
  onboarding: ['onboarding'] as const,
  extensions: { status: ['extensions', 'status'] as const, registry: ['extensions', 'registry'] as const, manifests: ['extensions', 'manifests'] as const },
  dashboard: ['dashboard'] as const,
  health: { agent: ['health', 'agent'] as const, system: ['health', 'system'] as const },
  updates: { check: ['updates', 'check'] as const, summary: ['updates', 'summary'] as const },
  plugins: ['plugins'] as const,
  mcp: { servers: ['mcp', 'servers'] as const, tools: ['mcp', 'tools'] as const },
  notes: { sources: ['notes', 'sources'] as const },
  approval: (sid: string) => ['approval', sid] as const,
  clarify: (sid: string) => ['clarify', sid] as const,
  background: (sid: string) => ['background', sid] as const,
  share: (token: string) => ['share', token] as const,
  streamStatus: (streamId: string) => ['stream', 'status', streamId] as const,
}
