/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppInsightsRouteImport } from './routes/_app.insights'
import { Route as AppKanbanRouteImport } from './routes/_app.kanban'
import { Route as AppLogsRouteImport } from './routes/_app.logs'
import { Route as AppMemoryRouteImport } from './routes/_app.memory'
import { Route as AppProfilesRouteImport } from './routes/_app.profiles'
import { Route as AppSessionsRouteImport } from './routes/_app.sessions'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSkillsRouteImport } from './routes/_app.skills'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppTodosRouteImport } from './routes/_app.todos'
import { Route as AppWorkspacesRouteImport } from './routes/_app.workspaces'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AppExtExtensionIdRouteImport } from './routes/_app.ext.$extensionId'
import { Route as AppSessionSessionIdRouteImport } from './routes/_app.session.$sessionId'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppSettingsSectionRouteImport } from './routes/_app.settings.$section'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppKanbanRoute = AppKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilesRoute = AppProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppTodosRoute = AppTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspacesRoute = AppWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AppRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppExtExtensionIdRoute = AppExtExtensionIdRouteImport.update({
  id: '/ext/$extensionId',
  path: '/ext/$extensionId',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionSessionIdRoute = AppSessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsSectionRoute = AppSettingsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AppSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/insights': typeof AppInsightsRoute
  '/kanban': typeof AppKanbanRoute
  '/logs': typeof AppLogsRoute
  '/memory': typeof AppMemoryRoute
  '/profiles': typeof AppProfilesRoute
  '/sessions': typeof AppSessionsRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/skills': typeof AppSkillsRoute
  '/tasks': typeof AppTasksRoute
  '/todos': typeof AppTodosRoute
  '/workspaces': typeof AppWorkspacesRoute
  '/share/$token': typeof ShareTokenRoute
  '/ext/$extensionId': typeof AppExtExtensionIdRoute
  '/session/$sessionId': typeof AppSessionSessionIdRoute
  '/settings/$section': typeof AppSettingsSectionRoute
  '/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/insights': typeof AppInsightsRoute
  '/kanban': typeof AppKanbanRoute
  '/logs': typeof AppLogsRoute
  '/memory': typeof AppMemoryRoute
  '/profiles': typeof AppProfilesRoute
  '/sessions': typeof AppSessionsRoute
  '/skills': typeof AppSkillsRoute
  '/tasks': typeof AppTasksRoute
  '/todos': typeof AppTodosRoute
  '/workspaces': typeof AppWorkspacesRoute
  '/share/$token': typeof ShareTokenRoute
  '/': typeof AppIndexRoute
  '/ext/$extensionId': typeof AppExtExtensionIdRoute
  '/session/$sessionId': typeof AppSessionSessionIdRoute
  '/settings/$section': typeof AppSettingsSectionRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/kanban': typeof AppKanbanRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/memory': typeof AppMemoryRoute
  '/_app/profiles': typeof AppProfilesRoute
  '/_app/sessions': typeof AppSessionsRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/skills': typeof AppSkillsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/todos': typeof AppTodosRoute
  '/_app/workspaces': typeof AppWorkspacesRoute
  '/share/$token': typeof ShareTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/ext/$extensionId': typeof AppExtExtensionIdRoute
  '/_app/session/$sessionId': typeof AppSessionSessionIdRoute
  '/_app/settings/$section': typeof AppSettingsSectionRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/insights'
    | '/kanban'
    | '/logs'
    | '/memory'
    | '/profiles'
    | '/sessions'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/todos'
    | '/workspaces'
    | '/share/$token'
    | '/ext/$extensionId'
    | '/session/$sessionId'
    | '/settings/$section'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/onboarding'
    | '/insights'
    | '/kanban'
    | '/logs'
    | '/memory'
    | '/profiles'
    | '/sessions'
    | '/skills'
    | '/tasks'
    | '/todos'
    | '/workspaces'
    | '/share/$token'
    | '/'
    | '/ext/$extensionId'
    | '/session/$sessionId'
    | '/settings/$section'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/insights'
    | '/_app/kanban'
    | '/_app/logs'
    | '/_app/memory'
    | '/_app/profiles'
    | '/_app/sessions'
    | '/_app/settings'
    | '/_app/skills'
    | '/_app/tasks'
    | '/_app/todos'
    | '/_app/workspaces'
    | '/share/$token'
    | '/_app/'
    | '/_app/ext/$extensionId'
    | '/_app/session/$sessionId'
    | '/_app/settings/$section'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kanban': {
      id: '/_app/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AppKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memory': {
      id: '/_app/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profiles': {
      id: '/_app/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof AppProfilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/todos': {
      id: '/_app/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof AppTodosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspaces': {
      id: '/_app/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AppWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ext/$extensionId': {
      id: '/_app/ext/$extensionId'
      path: '/ext/$extensionId'
      fullPath: '/ext/$extensionId'
      preLoaderRoute: typeof AppExtExtensionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/session/$sessionId': {
      id: '/_app/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof AppSessionSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/$section': {
      id: '/_app/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof AppSettingsSectionRouteImport
      parentRoute: typeof AppSettingsRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsSectionRoute: typeof AppSettingsSectionRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsSectionRoute: AppSettingsSectionRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppInsightsRoute: typeof AppInsightsRoute
  AppKanbanRoute: typeof AppKanbanRoute
  AppLogsRoute: typeof AppLogsRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppProfilesRoute: typeof AppProfilesRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppSkillsRoute: typeof AppSkillsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTodosRoute: typeof AppTodosRoute
  AppWorkspacesRoute: typeof AppWorkspacesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppExtExtensionIdRoute: typeof AppExtExtensionIdRoute
  AppSessionSessionIdRoute: typeof AppSessionSessionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInsightsRoute: AppInsightsRoute,
  AppKanbanRoute: AppKanbanRoute,
  AppLogsRoute: AppLogsRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppProfilesRoute: AppProfilesRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppSkillsRoute: AppSkillsRoute,
  AppTasksRoute: AppTasksRoute,
  AppTodosRoute: AppTodosRoute,
  AppWorkspacesRoute: AppWorkspacesRoute,
  AppIndexRoute: AppIndexRoute,
  AppExtExtensionIdRoute: AppExtExtensionIdRoute,
  AppSessionSessionIdRoute: AppSessionSessionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
