/**
 * The Hermes theme system: one token vocabulary, skins as data.
 *
 * Three tiers share the `--name` namespace so the extension skin protocol and the
 * Tailwind `@theme` map speak the same language:
 * - palette: the colours a skin is made of (`--bg`, `--accent`, `--border`, ...)
 * - semantic: roles derived from the palette (`--accent-fg`, `--link-color`, `--selection-bg`, ...)
 * - component: the few knobs components expose (`--composer-bg`, `--session-active-fg`, ...)
 *
 * `BASE` holds the value of every token for the light scheme plus the dark overrides;
 * each skin overrides a subset in `tokens` (both schemes) and `dark` (dark only), which
 * is exactly the cascade the legacy stylesheet built out of `:root`, `:root.dark`,
 * `:root[data-skin]` and `:root.dark[data-skin]`. No component rule mentions a skin;
 * skins that need a structural variant declare a trait (see `traits`).
 *
 * `renderThemeCss` turns this into the stylesheet the Vite plugin serves as
 * `virtual:hermes-theme.css`; `tailwind.css` maps the same names into utilities.
 */

export const TOKEN_NAMES = ['--bg', '--sidebar', '--border', '--border2', '--text', '--muted', '--accent', '--blue', '--gold', '--code-bg', '--surface', '--topbar-bg', '--main-bg', '--focus-ring', '--focus-glow', '--input-bg', '--hover-bg', '--strong', '--em', '--code-text', '--code-inline-bg', '--pre-text', '--accent-hover', '--accent-bg', '--accent-bg-strong', '--accent-text', '--error', '--success', '--warning', '--info', '--radius-sm', '--radius-md', '--radius-card', '--radius-lg', '--radius-pill', '--space-1', '--space-2', '--space-3', '--space-4', '--font-size-xs', '--font-size-sm', '--font-size-md', '--message-body-font-size', '--message-body-line-height', '--message-code-font-size', '--message-pre-code-font-size', '--message-table-font-size', '--file-tree-toggle-width', '--font-ui', '--font-conversation', '--font-mono', '--surface-subtle', '--surface-subtle-hover', '--border-subtle', '--border-muted', '--app-titlebar-safe-top', '--skeleton-base', '--skeleton-sheen', '--msg-rail', '--msg-max', '--chat-col-inset', '--user-bubble-bg', '--user-bubble-border', '--user-bubble-text', '--user-bubble-placeholder', '--user-selection-bg', '--user-selection-text', '--ease', '--dur', '--shadow-sm', '--shadow-md', '--r-sm', '--r-md', '--r-lg', '--canvas', '--island-ring', '--island-radius', '--island-gap', '--island-shadow', '--accent-fg', '--link-color', '--link-hover-glow', '--purple', '--amber', '--amber-strong', '--danger', '--panel-head-primary-fg', '--overlay-faint', '--overlay', '--overlay-strong', '--overlay-max', '--overlay-neutral', '--ink-overlay', '--scrim', '--dialog-bg', '--source-telegram', '--source-discord', '--source-slack', '--source-claude-code', '--scrollbar-thumb', '--scrollbar-thumb-hover', '--selection-bg', '--selection-fg', '--root-font-size', '--root-line-height', '--body-weight', '--body-tracking', '--text-rendering', '--msg-tracking', '--msg-code-size', '--heading-tracking', '--titlebar-title-tracking', '--composer-font-size', '--composer-line-height', '--composer-tracking', '--composer-scrollbar-width', '--composer-scrollbar-display', '--body-bg', '--rail-bg', '--titlebar-bg', '--titlebar-border', '--sidebar-bg', '--sidebar-border', '--sidebar-border-style', '--sidebar-shadow', '--main-surface', '--pane-bg', '--island-ring-width', '--chrome-backdrop', '--control-radius', '--composer-wrap-bg', '--composer-wrap-border-top', '--composer-bg', '--composer-border-color', '--composer-border-width', '--composer-radius', '--composer-shadow', '--composer-focus-border', '--composer-focus-shadow', '--chip-bg', '--chip-border', '--chip-fg', '--chip-hover-bg', '--chip-hover-border', '--chip-hover-fg', '--ws-chip-hover-bg', '--ws-chip-hover-border', '--ws-chip-hover-fg', '--send-bg', '--send-fg', '--send-shadow', '--send-weight', '--send-hover-bg', '--send-hover-shadow', '--send-disabled-bg', '--send-disabled-fg', '--send-disabled-opacity', '--primary-bg', '--primary-fg', '--primary-border', '--primary-hover-bg', '--primary-hover-border', '--primary-hover-transform', '--primary-hover-shadow', '--float-btn-bg', '--float-shadow', '--scroll-btn-bg', '--scroll-btn-shadow', '--btn-radius', '--rail-btn-radius', '--nav-tab-radius', '--nav-tab-radius-mobile', '--input-radius', '--chip-radius', '--session-radius', '--icon-btn-hover-bg', '--project-chip-hover-bg', '--file-item-hover-bg', '--project-chip-bg', '--project-chip-border', '--project-chip-active-bg', '--project-chip-active-fg', '--project-chip-active-border', '--project-chip-active-shadow', '--project-chip-active-weight', '--select-border', '--input-focus-border', '--input-focus-shadow', '--search-bg', '--search-border', '--search-focus-bg', '--search-focus-shadow', '--table-border', '--table-head-border', '--pre-bg', '--pre-border', '--msg-role-user-fg', '--assistant-msg-bg', '--user-msg-bg', '--user-msg-border', '--user-msg-rail-width', '--user-msg-rail', '--user-msg-radius', '--user-msg-fg', '--user-msg-padding', '--user-msg-weight', '--user-msg-size', '--user-msg-code-bg', '--tool-running-bg', '--tool-running-border', '--session-font-size', '--session-line-height', '--session-hover-bg', '--session-active-bg', '--session-active-fg', '--session-active-border', '--session-active-rail-width', '--session-active-rail-color', '--session-active-shadow', '--session-active-weight', '--session-active-title-fg', '--session-active-meta-fg', '--session-bar-color', '--session-bar-radius', '--session-bar-inset-y', '--session-bar-left', '--session-bar-opacity', '--session-pinned-fg', '--session-trigger-active-fg', '--pick-active-bg', '--pick-active-border', '--pick-active-shadow', '--pick-active-fg', '--pick-active-weight', '--settings-section-bg', '--menu-active-bg', '--menu-active-fg', '--menu-active-shadow', '--menu-active-weight', '--nav-active-bg', '--nav-active-fg', '--nav-active-shadow', '--nav-active-weight', '--nav-active-icon-fg', '--nav-hover-bg', '--nav-tooltip-fg', '--rail-active-bg', '--rail-active-fg', '--rail-active-shadow', '--rail-active-weight', '--rail-active-icon-fg', '--panel-btn-hover-bg', '--panel-btn-hover-fg'] as const
export type TokenName = (typeof TOKEN_NAMES)[number]
export type TokenMap = Partial<Record<TokenName, string>>

/** Structural variants a skin can opt into; each has a rule block in theme.css. */
export const SKIN_TRAITS = ['square-controls', 'card-sessions'] as const
export type SkinTrait = (typeof SKIN_TRAITS)[number]

export interface SkinSpec {
  key: string
  name: string
  /** Picker swatch: up to three colours. */
  colors: readonly string[]
  traits?: readonly SkinTrait[]
  /** Values for both schemes (`:root[data-skin]`). */
  tokens: TokenMap
  /** Dark-scheme overrides (`:root.dark[data-skin]`). */
  dark: TokenMap
}

/** Every token, light values; `dark` lists the ones that change in the dark scheme. */
export const BASE: { tokens: Record<TokenName, string>; dark: TokenMap } = {
  tokens: {
    '--bg': '#FEFCF7',
    '--sidebar': '#FAF7F0',
    '--border': '#E0D8C8',
    '--border2': 'rgba(0,0,0,0.15)',
    '--text': '#1A1610',
    '--muted': '#5C5344',
    '--accent': '#B8860B',
    '--blue': '#0288A8',
    '--gold': '#8B6508',
    '--code-bg': '#F5F0E5',
    '--surface': '#F3EEE3',
    '--topbar-bg': 'rgba(250,247,240,.98)',
    '--main-bg': 'rgba(254,252,247,0.5)',
    '--focus-ring': 'rgba(184,134,11,.35)',
    '--focus-glow': 'rgba(184,134,11,.1)',
    '--input-bg': 'rgba(0,0,0,.03)',
    '--hover-bg': 'rgba(0,0,0,.05)',
    '--strong': '#0F0D08',
    '--em': '#5C5344',
    '--code-text': '#8b4513',
    '--code-inline-bg': 'rgba(0,0,0,.06)',
    '--pre-text': '#1A1610',
    '--accent-hover': '#996F08',
    '--accent-bg': 'rgba(184,134,11,0.08)',
    '--accent-bg-strong': 'rgba(184,134,11,0.15)',
    '--accent-text': '#8B6508',
    '--error': '#C62828',
    '--success': '#3D8B40',
    '--warning': '#E68A00',
    '--info': '#0288A8',
    '--radius-sm': '4px',
    '--radius-md': '8px',
    '--radius-card': '8px',
    '--radius-lg': '12px',
    '--radius-pill': '999px',
    '--space-1': '4px',
    '--space-2': '8px',
    '--space-3': '12px',
    '--space-4': '16px',
    '--font-size-xs': '11px',
    '--font-size-sm': '12px',
    '--font-size-md': '14px',
    '--message-body-font-size': '14px',
    '--message-body-line-height': '1.55',
    '--message-code-font-size': '12.5px',
    '--message-pre-code-font-size': '13px',
    '--message-table-font-size': '12px',
    '--file-tree-toggle-width': '10px',
    '--font-ui': '\"Inter\",ui-sans-serif,system-ui,-apple-system,\"Segoe UI\",sans-serif',
    '--font-conversation': 'var(--font-ui)',
    '--font-mono': 'ui-monospace,\"SFMono-Regular\",\"SF Mono\",Menlo,Consolas,\"Liberation Mono\",monospace',
    '--surface-subtle': 'rgba(0,0,0,.025)',
    '--surface-subtle-hover': 'rgba(0,0,0,.045)',
    '--border-subtle': 'color-mix(in srgb, var(--border) 60%, transparent)',
    '--border-muted': 'rgba(0,0,0,.12)',
    '--app-titlebar-safe-top': '0px',
    '--skeleton-base': 'color-mix(in srgb,var(--text) 8%,transparent)',
    '--skeleton-sheen': 'color-mix(in srgb,var(--text) 22%,transparent)',
    '--msg-rail': '0',
    '--msg-max': '768px',
    '--chat-col-inset': 'max(20px, calc((100% - var(--msg-max)) / 2 + 20px))',
    '--user-bubble-bg': 'var(--accent)',
    '--user-bubble-border': 'var(--accent-hover)',
    '--user-bubble-text': '#fff',
    '--user-bubble-placeholder': 'rgba(255,255,255,.7)',
    '--user-selection-bg': 'rgba(0,0,0,.22)',
    '--user-selection-text': '#fff',
    '--ease': 'ease',
    '--dur': '.15s',
    '--shadow-sm': '0 1px 2px rgba(0,0,0,.06)',
    '--shadow-md': '0 2px 8px rgba(0,0,0,.08)',
    '--r-sm': '6px',
    '--r-md': '8px',
    '--r-lg': '12px',
    // Inset shell (shadcn sidebar variant="inset"): rail + sidebar sit on the frame tone; main is a rounded, shadowed card with no ring.
    '--canvas': 'var(--sidebar)',
    '--island-ring': 'var(--border)',
    '--island-radius': '12px',
    '--island-gap': '8px',
    '--island-shadow': '0 1px 3px rgba(0,0,0,.1),0 1px 2px -1px rgba(0,0,0,.1)',
    '--accent-fg': '#fff',
    '--link-color': 'var(--blue)',
    '--link-hover-glow': 'none',
    '--purple': '#8b5cf6',
    '--amber': '#f59e0b',
    '--amber-strong': '#fbbf24',
    '--danger': 'var(--error)',
    '--panel-head-primary-fg': '#fff',
    '--overlay-faint': 'rgba(255,255,255,.03)',
    '--overlay': 'rgba(255,255,255,.08)',
    '--overlay-strong': 'rgba(255,255,255,.12)',
    '--overlay-max': 'rgba(255,255,255,.22)',
    '--overlay-neutral': 'rgba(127,127,127,.22)',
    '--ink-overlay': 'rgba(0,0,0,.1)',
    '--scrim': 'rgba(7,12,19,.78)',
    '--dialog-bg': 'linear-gradient(180deg,rgba(20,30,44,.98),rgba(11,17,27,.98))',
    '--source-telegram': 'rgba(0,136,204,.55)',
    '--source-discord': '#5865F2',
    '--source-slack': '#4A154B',
    '--source-claude-code': 'rgba(217,119,6,.65)',
    '--scrollbar-thumb': 'rgba(0,0,0,.15)',
    '--scrollbar-thumb-hover': 'rgba(0,0,0,.3)',
    '--selection-bg': 'var(--accent-bg-strong)',
    '--selection-fg': 'currentColor',
    '--root-font-size': '14px',
    '--root-line-height': '1.6',
    '--body-weight': '400',
    '--body-tracking': '-.006em',
    '--text-rendering': 'auto',
    '--msg-tracking': '-.004em',
    '--msg-code-size': 'var(--message-code-font-size)',
    '--heading-tracking': '-.015em',
    '--titlebar-title-tracking': '-.01em',
    '--composer-font-size': '16px',
    '--composer-line-height': '1.65',
    '--composer-tracking': 'normal',
    '--composer-scrollbar-width': 'auto',
    '--composer-scrollbar-display': 'block',
    '--body-bg': 'var(--canvas)',
    '--rail-bg': 'transparent',
    '--titlebar-bg': 'transparent',
    '--titlebar-border': 'var(--border)',
    '--sidebar-bg': 'var(--sidebar)',
    '--sidebar-border': 'var(--island-ring)',
    '--sidebar-border-style': 'solid',
    '--sidebar-shadow': 'none',
    '--main-surface': 'var(--bg)',
    '--pane-bg': 'transparent',
    '--island-ring-width': '0',
    '--chrome-backdrop': 'none',
    '--control-radius': '6px',
    '--composer-wrap-bg': 'var(--sidebar)',
    '--composer-wrap-border-top': '1px solid var(--border)',
    '--composer-bg': 'var(--bg)',
    '--composer-border-color': 'rgba(0,0,0,.12)',
    '--composer-border-width': '1px',
    '--composer-radius': 'var(--r-lg)',
    '--composer-shadow': '0 1px 2px rgba(0,0,0,.04)',
    '--composer-focus-border': 'color-mix(in srgb,var(--accent) 50%,transparent)',
    '--composer-focus-shadow': '0 0 0 1px color-mix(in srgb,var(--accent) 20%,transparent)',
    '--chip-bg': 'transparent',
    '--chip-border': 'var(--border)',
    '--chip-fg': 'var(--muted)',
    '--chip-hover-bg': 'var(--hover-bg)',
    '--chip-hover-border': 'var(--border)',
    '--chip-hover-fg': 'var(--text)',
    '--ws-chip-hover-bg': 'transparent',
    '--ws-chip-hover-border': 'transparent',
    '--ws-chip-hover-fg': 'var(--muted)',
    '--send-bg': 'var(--accent)',
    '--send-fg': 'var(--accent-fg)',
    '--send-shadow': 'none',
    '--send-weight': 'inherit',
    '--send-hover-bg': 'var(--accent-hover)',
    '--send-hover-shadow': 'none',
    '--send-disabled-bg': 'var(--surface-subtle-hover)',
    '--send-disabled-fg': 'var(--muted)',
    '--send-disabled-opacity': '.7',
    '--primary-bg': 'var(--accent-bg)',
    '--primary-fg': 'var(--accent-text)',
    '--primary-border': 'var(--accent)',
    '--primary-hover-bg': 'var(--accent-bg-strong)',
    '--primary-hover-border': 'var(--accent)',
    '--primary-hover-transform': 'translateY(-1px)',
    '--primary-hover-shadow': '0 2px 8px rgba(0,0,0,.2)',
    '--float-btn-bg': 'var(--surface)',
    '--float-shadow': 'var(--shadow-md)',
    '--scroll-btn-bg': 'var(--code-bg)',
    '--scroll-btn-shadow': '0 2px 8px rgba(0,0,0,.25)',
    '--btn-radius': 'var(--r-sm)',
    '--rail-btn-radius': 'var(--r-md)',
    '--nav-tab-radius': '0',
    '--nav-tab-radius-mobile': '10px',
    '--input-radius': 'var(--r-md)',
    '--chip-radius': '12px',
    '--session-radius': '7px',
    '--icon-btn-hover-bg': 'rgba(0,0,0,.06)',
    '--project-chip-hover-bg': 'var(--hover-bg)',
    '--file-item-hover-bg': 'rgba(0,0,0,.04)',
    '--project-chip-bg': 'rgba(0,0,0,.04)',
    '--project-chip-border': 'rgba(0,0,0,.12)',
    '--project-chip-active-bg': 'var(--accent-bg)',
    '--project-chip-active-fg': 'var(--accent-text)',
    '--project-chip-active-border': 'var(--accent-bg-strong)',
    '--project-chip-active-shadow': 'none',
    '--project-chip-active-weight': 'inherit',
    '--select-border': 'rgba(0,0,0,.12)',
    '--input-focus-border': 'var(--accent)',
    '--input-focus-shadow': '0 0 0 1px var(--accent)',
    '--search-bg': 'rgba(0,0,0,.03)',
    '--search-border': 'rgba(0,0,0,.1)',
    '--search-focus-bg': 'rgba(0,0,0,.02)',
    '--search-focus-shadow': '0 0 0 3px var(--accent-bg)',
    '--table-border': 'rgba(0,0,0,.08)',
    '--table-head-border': 'rgba(0,0,0,.16)',
    '--pre-bg': 'var(--code-bg)',
    '--pre-border': '1px solid var(--border)',
    '--msg-role-user-fg': 'var(--accent-text)',
    '--assistant-msg-bg': 'transparent',
    '--user-msg-bg': 'var(--surface-subtle)',
    '--user-msg-border': '1px solid var(--border-subtle)',
    '--user-msg-rail-width': '0',
    '--user-msg-rail': 'var(--accent)',
    '--user-msg-radius': '18px',
    '--user-msg-fg': 'var(--text)',
    '--user-msg-padding': '10px 16px',
    '--user-msg-weight': '400',
    '--user-msg-size': 'var(--message-body-font-size)',
    '--user-msg-code-bg': 'var(--code-inline-bg)',
    '--tool-running-bg': 'transparent',
    '--tool-running-border': 'transparent',
    '--session-font-size': '13px',
    '--session-line-height': 'normal',
    '--session-hover-bg': 'var(--hover-bg)',
    '--session-active-bg': 'var(--accent-bg)',
    '--session-active-fg': 'var(--accent-text)',
    '--session-active-border': '0',
    '--session-active-rail-width': '0',
    '--session-active-rail-color': 'transparent',
    '--session-active-shadow': 'none',
    '--session-active-weight': 'inherit',
    '--session-active-title-fg': 'var(--accent-text)',
    '--session-active-meta-fg': 'var(--muted)',
    '--session-bar-color': 'var(--accent)',
    '--session-bar-radius': '1px',
    '--session-bar-inset-y': '8px',
    '--session-bar-left': '-6px',
    '--session-bar-opacity': '1',
    '--session-pinned-fg': 'var(--accent-text)',
    '--session-trigger-active-fg': 'var(--accent-text)',
    '--pick-active-bg': 'var(--accent-bg)',
    '--pick-active-border': 'var(--accent)',
    '--pick-active-shadow': 'none',
    '--pick-active-fg': 'inherit',
    '--pick-active-weight': 'inherit',
    '--settings-section-bg': 'transparent',
    '--menu-active-bg': 'var(--accent-bg)',
    '--menu-active-fg': 'var(--accent-text)',
    '--menu-active-shadow': 'none',
    '--menu-active-weight': '600',
    '--nav-active-bg': 'transparent',
    '--nav-active-fg': 'var(--accent-text)',
    '--nav-active-shadow': 'none',
    '--nav-active-weight': 'inherit',
    '--nav-active-icon-fg': 'currentColor',
    '--nav-hover-bg': 'transparent',
    '--nav-tooltip-fg': 'var(--accent-text)',
    '--rail-active-bg': 'var(--accent-bg)',
    '--rail-active-fg': 'var(--accent-text)',
    '--rail-active-shadow': 'none',
    '--rail-active-weight': 'inherit',
    '--rail-active-icon-fg': 'currentColor',
    '--panel-btn-hover-bg': 'var(--accent-bg)',
    '--panel-btn-hover-fg': 'var(--accent-text)',
  },
  dark: {
    '--canvas': 'var(--surface)',
    '--user-msg-border': '0',
    '--user-msg-bg': 'rgba(255,255,255,.07)',
    '--bg': '#0D0D1A',
    '--sidebar': '#141425',
    '--border': '#2A2A45',
    '--border2': 'rgba(255,255,255,0.14)',
    '--text': '#FFF8DC',
    '--muted': '#C0C0C0',
    '--accent': '#FFD700',
    '--blue': '#4DD0E1',
    '--gold': '#FFBF00',
    '--code-bg': '#1A1A2E',
    '--surface': '#1A1A2E',
    '--topbar-bg': 'rgba(20,20,37,.98)',
    '--main-bg': 'rgba(13,13,26,0.5)',
    '--focus-ring': 'rgba(255,215,0,.35)',
    '--focus-glow': 'rgba(255,215,0,.08)',
    '--input-bg': 'rgba(255,255,255,.04)',
    '--hover-bg': 'rgba(255,255,255,.06)',
    '--strong': '#fff',
    '--em': '#C0C0C0',
    '--code-text': '#f0c27f',
    '--code-inline-bg': 'rgba(0,0,0,.35)',
    '--pre-text': '#e2e8f0',
    '--accent-hover': '#FFBF00',
    '--accent-bg': 'rgba(255,215,0,0.08)',
    '--accent-bg-strong': 'rgba(255,215,0,0.15)',
    '--accent-text': '#FFD700',
    '--error': '#EF5350',
    '--success': '#4CAF50',
    '--warning': '#FFA726',
    '--info': '#4DD0E1',
    '--surface-subtle': 'rgba(255,255,255,.025)',
    '--surface-subtle-hover': 'rgba(255,255,255,.045)',
    '--border-subtle': 'color-mix(in srgb, var(--border) 60%, transparent)',
    '--border-muted': 'rgba(255,255,255,.12)',
    '--skeleton-base': 'color-mix(in srgb,#fff 6%,transparent)',
    '--skeleton-sheen': 'color-mix(in srgb,#fff 20%,transparent)',
    '--user-bubble-bg': 'var(--accent-bg-strong)',
    '--user-bubble-border': 'var(--accent-bg-strong)',
    '--user-bubble-text': 'var(--text)',
    '--user-bubble-placeholder': 'var(--muted)',
    '--user-selection-bg': 'rgba(255,255,255,.18)',
    '--user-selection-text': 'var(--text)',
    '--panel-head-primary-fg': 'var(--bg)',
    '--shadow-sm': '0 1px 2px rgba(0,0,0,.3)',
    '--shadow-md': '0 2px 8px rgba(0,0,0,.4)',
    '--accent-fg': '#1A1406',
    '--scrollbar-thumb': 'rgba(255,255,255,.12)',
    '--scrollbar-thumb-hover': 'rgba(255,255,255,.22)',
    '--selection-bg': 'Highlight',
    '--selection-fg': 'HighlightText',
    '--composer-wrap-bg': 'var(--bg)',
    '--composer-wrap-border-top': 'none',
    '--composer-bg': 'var(--surface)',
    '--composer-border-color': 'var(--border)',
    '--composer-shadow': 'inset 0 1px 0 rgba(255,255,255,.04)',
    '--composer-focus-shadow': '0 0 0 1px color-mix(in srgb,var(--accent) 25%,transparent)',
    '--icon-btn-hover-bg': 'var(--overlay)',
    '--project-chip-hover-bg': 'var(--overlay)',
    '--file-item-hover-bg': 'var(--hover-bg)',
    '--project-chip-bg': 'var(--input-bg)',
    '--project-chip-border': 'var(--border2)',
    '--project-chip-active-border': 'var(--accent-bg)',
    '--select-border': 'transparent',
    '--search-bg': 'var(--bg)',
    '--search-border': 'var(--border)',
    '--search-focus-bg': 'var(--bg)',
    '--table-border': 'var(--border)',
    '--table-head-border': 'var(--border2)',
    '--msg-role-user-fg': 'var(--accent)',
    '--session-active-bg': 'var(--surface-subtle-hover)',
    '--session-active-fg': 'var(--accent)',
    '--session-pinned-fg': 'var(--accent)',
    '--session-trigger-active-fg': 'var(--text)',
    '--nav-tooltip-fg': 'var(--text)',
  },
}

export const SKINS = [
  {
    key: 'codex',
    name: 'Codex',
    colors: ['#72B39A','#242624','#ECEBE4'],
    traits: ['card-sessions'],
    tokens: {
      '--bg': '#FFFFFF',
      '--sidebar': '#F3F3F3',
      '--surface': '#FFFFFF',
      '--surface-subtle': '#F1F1F1',
      '--surface-subtle-hover': '#E9E9E9',
      '--border': '#E0E0E0',
      '--border2': '#C8C8C8',
      '--border-subtle': '#E8E8E8',
      '--border-muted': '#DADADA',
      '--text': '#252523',
      '--strong': '#111110',
      '--muted': '#6A6A68',
      '--em': '#3A3A38',
      '--accent': '#2E7A60',
      '--accent-hover': '#1D6850',
      '--accent-bg': 'rgba(46,122,96,0.08)',
      '--accent-bg-strong': 'rgba(46,122,96,0.16)',
      '--accent-text': '#1D6850',
      '--blue': '#4D8DFF',
      '--gold': '#2E7A60',
      '--focus-ring': 'rgba(46,122,96,0.25)',
      '--focus-glow': 'rgba(46,122,96,0.10)',
      '--input-bg': '#FFFFFF',
      '--hover-bg': 'rgba(0,0,0,0.04)',
      '--code-bg': '#F3F3F3',
      '--code-inline-bg': 'rgba(0,0,0,0.06)',
      '--code-text': '#252523',
      '--pre-text': '#252523',
      '--topbar-bg': 'rgba(255,255,255,0.96)',
      '--main-bg': '#FFFFFF',
      '--error': '#D92D20',
      '--success': '#2E7A60',
      '--warning': '#B87916',
      '--info': '#4D8DFF',
      '--user-bubble-bg': '#EBEBEB',
      '--user-bubble-border': '#D9D9D9',
      '--user-bubble-text': '#252523',
      '--user-bubble-placeholder': '#6A6A68',
      '--user-selection-bg': 'rgba(46,122,96,0.20)',
      '--user-selection-text': '#0D0D0D',
      '--font-ui': '-apple-system,BlinkMacSystemFont,\"Segoe UI\",sans-serif',
      '--body-weight': '430',
      '--body-tracking': '0',
      '--text-rendering': 'optimizeLegibility',
      '--body-bg': 'var(--bg)',
      '--canvas': 'var(--sidebar)',
      '--rail-bg': 'var(--sidebar)',
      '--titlebar-bg': 'var(--sidebar)',
      '--sidebar-border': 'var(--border)',
      '--pane-bg': 'var(--bg)',
      '--composer-wrap-bg': 'var(--sidebar)',
      '--composer-bg': 'var(--surface)',
      '--composer-border-color': 'var(--border2)',
      '--composer-radius': '14px',
      '--composer-shadow': '0 1px 2px rgba(0,0,0,.07)',
      '--composer-focus-border': 'var(--accent)',
      '--composer-focus-shadow': '0 0 0 2px var(--focus-ring)',
      '--composer-font-size': '14px',
      '--composer-line-height': '1.45',
      '--composer-tracking': '0',
      '--msg-tracking': '0',
      '--msg-code-size': '.92em',
      '--link-color': 'var(--accent-text)',
      '--user-msg-bg': 'var(--user-bubble-bg)', '--user-msg-weight': 'var(--body-weight)', '--user-msg-size': 'var(--message-body-font-size)', '--user-msg-padding': '8px 12px',
      '--user-msg-rail': 'var(--user-bubble-border)',
      '--user-msg-radius': '12px',
      '--user-msg-fg': 'var(--user-bubble-text)',
      '--scroll-btn-bg': 'var(--surface)',
      '--scroll-btn-shadow': '0 1px 2px rgba(0,0,0,.08)',
      '--float-shadow': '0 1px 2px rgba(0,0,0,.08)',
      '--send-weight': '600',
      '--session-radius': '8px',
      '--session-font-size': '12.5px',
      '--session-line-height': '1.42',
      '--session-active-bg': 'var(--surface-subtle-hover)',
      '--session-active-fg': 'var(--text)',
      '--session-active-border': '1px solid var(--border)',
      '--session-active-rail-width': '1px',
      '--session-active-rail-color': 'var(--border)',
      '--session-active-title-fg': 'inherit',
      '--session-active-meta-fg': 'inherit',
      '--session-bar-color': 'color-mix(in srgb,var(--accent) 70%,var(--border2))',
      '--session-bar-radius': '999px',
      '--session-bar-inset-y': '12px',
      '--session-bar-left': '7px',
      '--session-bar-opacity': '.55',
      '--pick-active-bg': 'var(--surface)',
      '--pick-active-border': 'var(--border2)',
      '--pick-active-shadow': 'inset 0 0 0 1px var(--accent)',
      '--heading-tracking': '0',
      '--titlebar-title-tracking': '0',
      '--tool-running-bg': 'var(--accent-bg)',
      '--tool-running-border': 'var(--accent-bg-strong)',
    },
    dark: {
      '--bg': '#151614',
      '--sidebar': '#242624',
      '--surface': '#1B1C1A',
      '--surface-subtle': '#20211F',
      '--surface-subtle-hover': '#292B28',
      '--border': '#343631',
      '--border2': '#4B4D47',
      '--border-subtle': '#2A2C28',
      '--border-muted': '#3D3F3A',
      '--text': '#ECEBE4',
      '--strong': '#FAF9F3',
      '--muted': '#A7A79D',
      '--em': '#D7D6CE',
      '--accent': '#72B39A',
      '--accent-hover': '#84BEA8',
      '--accent-bg': 'rgba(114,179,154,0.10)',
      '--accent-bg-strong': 'rgba(114,179,154,0.18)',
      '--accent-text': '#84BEA8',
      '--blue': '#C9C8C0',
      '--gold': '#72B39A',
      '--focus-ring': 'rgba(114,179,154,0.30)',
      '--focus-glow': 'rgba(114,179,154,0.12)',
      '--input-bg': '#1E1F1D',
      '--hover-bg': 'rgba(255,255,255,0.06)',
      '--code-bg': '#111210',
      '--code-inline-bg': 'rgba(255,255,255,0.08)',
      '--code-text': '#F1F0EA',
      '--pre-text': '#ECEBE4',
      '--topbar-bg': 'rgba(21,22,20,0.92)',
      '--main-bg': '#151614',
      '--error': '#FF6B6B',
      '--success': '#72B39A',
      '--warning': '#E6B15C',
      '--info': '#C9C8C0',
      '--user-bubble-bg': '#2E302D',
      '--user-bubble-border': '#454741',
      '--user-bubble-text': '#F4F3EC',
      '--user-bubble-placeholder': '#A7A79D',
      '--user-selection-bg': 'rgba(114,179,154,0.22)',
      '--user-selection-text': '#FAF9F3',
      '--accent-fg': '#0D0D0D',
      '--composer-shadow': '0 1px 2px rgba(0,0,0,.28)',
      '--scroll-btn-shadow': '0 1px 2px rgba(0,0,0,.28)',
      '--float-shadow': '0 1px 2px rgba(0,0,0,.28)',
    },
  },
  {
    key: 'terracotta',
    name: 'Terracotta',
    colors: ['#D97757','#F0EEE6','#141413'],
    traits: ['card-sessions'],
    tokens: {
      '--bg': '#FAF9F5',
      '--sidebar': '#F0EEE6',
      '--surface': '#FFFEFA',
      '--surface-subtle': '#F7F4EC',
      '--surface-subtle-hover': '#EEE9DE',
      '--border': '#E8E6DC',
      '--border2': '#D7D2C4',
      '--border-subtle': '#F0EDE4',
      '--border-muted': '#DDD8CA',
      '--text': '#30302E',
      '--strong': '#141413',
      '--muted': '#87867F',
      '--em': '#3D3D3A',
      '--accent': '#D97757',
      '--accent-hover': '#C76345',
      '--accent-bg': 'rgba(217,119,87,0.10)',
      '--accent-bg-strong': 'rgba(217,119,87,0.18)',
      '--accent-text': '#A94F35',
      '--blue': '#6396D6',
      '--gold': '#D97757',
      '--focus-ring': 'rgba(217,119,87,0.28)',
      '--focus-glow': 'rgba(217,119,87,0.10)',
      '--input-bg': '#FFFEFA',
      '--hover-bg': 'rgba(48,48,46,0.05)',
      '--code-bg': '#F0EEE6',
      '--code-inline-bg': 'rgba(48,48,46,0.065)',
      '--code-text': '#30302E',
      '--pre-text': '#30302E',
      '--topbar-bg': 'rgba(250,249,245,0.96)',
      '--main-bg': '#FAF9F5',
      '--error': '#C15F3C',
      '--success': '#6EA100',
      '--warning': '#B87916',
      '--info': '#6396D6',
      '--user-bubble-bg': '#F0EEE6',
      '--user-bubble-border': '#E2DED2',
      '--user-bubble-text': '#30302E',
      '--user-bubble-placeholder': '#87867F',
      '--user-selection-bg': 'rgba(217,119,87,0.24)',
      '--user-selection-text': '#141413',
      '--font-ui': '-apple-system,BlinkMacSystemFont,\"Segoe UI\",sans-serif',
      '--body-weight': '430',
      '--body-tracking': '0',
      '--text-rendering': 'optimizeLegibility',
      '--body-bg': 'var(--bg)',
      '--canvas': 'var(--sidebar)',
      '--rail-bg': 'var(--sidebar)',
      '--titlebar-bg': 'var(--sidebar)',
      '--sidebar-border': 'var(--border)',
      '--pane-bg': 'var(--bg)',
      '--composer-wrap-bg': 'var(--sidebar)',
      '--composer-bg': 'var(--surface)',
      '--composer-border-color': 'var(--border2)',
      '--composer-radius': '14px',
      '--composer-shadow': '0 1px 2px rgba(0,0,0,.07)',
      '--composer-focus-border': 'var(--accent)',
      '--composer-focus-shadow': '0 0 0 2px var(--focus-ring)',
      '--composer-font-size': '14px',
      '--composer-line-height': '1.45',
      '--composer-tracking': '0',
      '--msg-tracking': '0',
      '--msg-code-size': '.92em',
      '--link-color': 'var(--accent-text)',
      '--user-msg-bg': 'var(--user-bubble-bg)', '--user-msg-weight': 'var(--body-weight)', '--user-msg-size': 'var(--message-body-font-size)', '--user-msg-padding': '8px 12px',
      '--user-msg-rail': 'var(--user-bubble-border)',
      '--user-msg-radius': '12px',
      '--user-msg-fg': 'var(--user-bubble-text)',
      '--scroll-btn-bg': 'var(--surface)',
      '--scroll-btn-shadow': '0 1px 2px rgba(0,0,0,.08)',
      '--float-shadow': '0 1px 2px rgba(0,0,0,.08)',
      '--send-weight': '600',
      '--session-radius': '8px',
      '--session-font-size': '12.5px',
      '--session-line-height': '1.42',
      '--session-active-bg': 'var(--surface-subtle-hover)',
      '--session-active-fg': 'var(--text)',
      '--session-active-border': '1px solid var(--border)',
      '--session-active-rail-width': '1px',
      '--session-active-rail-color': 'var(--border)',
      '--session-active-title-fg': 'inherit',
      '--session-active-meta-fg': 'inherit',
      '--session-bar-color': 'color-mix(in srgb,var(--accent) 70%,var(--border2))',
      '--session-bar-radius': '999px',
      '--session-bar-inset-y': '12px',
      '--session-bar-left': '7px',
      '--session-bar-opacity': '.55',
      '--pick-active-bg': 'var(--surface)',
      '--pick-active-border': 'var(--border2)',
      '--pick-active-shadow': 'inset 0 0 0 1px var(--accent)',
      '--heading-tracking': '0',
      '--titlebar-title-tracking': '0',
      '--tool-running-bg': 'var(--accent-bg)',
      '--tool-running-border': 'var(--accent-bg-strong)',
    },
    dark: {
      '--bg': '#141413',
      '--sidebar': '#1E1D1A',
      '--surface': '#191917',
      '--surface-subtle': '#20201D',
      '--surface-subtle-hover': '#2A2925',
      '--border': '#34332E',
      '--border2': '#4A473F',
      '--border-subtle': '#292824',
      '--border-muted': '#3D3A34',
      '--text': '#EDEAE0',
      '--strong': '#FAF9F5',
      '--muted': '#B0AEA5',
      '--em': '#D8D4C8',
      '--accent': '#D97757',
      '--accent-hover': '#E69072',
      '--accent-bg': 'rgba(217,119,87,0.11)',
      '--accent-bg-strong': 'rgba(217,119,87,0.20)',
      '--accent-text': '#E69072',
      '--blue': '#7BA7DE',
      '--gold': '#D97757',
      '--focus-ring': 'rgba(217,119,87,0.30)',
      '--focus-glow': 'rgba(217,119,87,0.12)',
      '--input-bg': '#191917',
      '--hover-bg': 'rgba(237,234,224,0.055)',
      '--code-bg': '#10100F',
      '--code-inline-bg': 'rgba(237,234,224,0.08)',
      '--code-text': '#F0EEE6',
      '--pre-text': '#EDEAE0',
      '--topbar-bg': 'rgba(20,20,19,0.94)',
      '--main-bg': '#141413',
      '--error': '#F08A6F',
      '--success': '#9BCB5A',
      '--warning': '#E6B15C',
      '--info': '#7BA7DE',
      '--user-bubble-bg': '#282620',
      '--user-bubble-border': '#464238',
      '--user-bubble-text': '#FAF9F5',
      '--user-bubble-placeholder': '#B0AEA5',
      '--user-selection-bg': 'rgba(217,119,87,0.24)',
      '--user-selection-text': '#FAF9F5',
      '--accent-fg': '#141413',
      '--composer-shadow': '0 1px 2px rgba(0,0,0,.28)',
      '--scroll-btn-shadow': '0 1px 2px rgba(0,0,0,.28)',
      '--float-shadow': '0 1px 2px rgba(0,0,0,.28)',
    },
  },
  {
    key: 'default',
    name: 'Default',
    colors: ['#FFD700','#FFBF00','#CD7F32'],
    tokens: {
      '--bg': '#FFFFFF',
      '--sidebar': '#FAFAFB',
      '--surface': '#FFFFFF',
      '--code-bg': '#F3F3F5',
      '--main-bg': '#FFFFFF',
      '--border': 'rgba(0,0,0,.08)',
      '--border2': 'rgba(0,0,0,.14)',
      '--border-subtle': 'rgba(0,0,0,.05)',
      '--border-muted': 'rgba(0,0,0,.1)',
      '--surface-subtle': 'rgba(0,0,0,.03)',
      '--surface-subtle-hover': 'rgba(0,0,0,.05)',
      '--input-bg': 'rgba(0,0,0,.025)',
      '--hover-bg': 'rgba(0,0,0,.045)',
      '--topbar-bg': '#FFFFFF',
      '--text': '#18181B',
      '--muted': '#71717A',
      '--strong': '#000000',
      '--code-text': '#7A4F0C',
      '--code-inline-bg': '#F0F0F3',
      '--user-bubble-bg': '#EDEDF0',
      '--user-bubble-border': '#EDEDF0',
      '--user-bubble-text': '#111114',
      '--user-bubble-placeholder': '#6B6B74',
      '--island-ring': 'rgba(0,0,0,.07)',
    },
    dark: {
      '--bg': '#111113',
      '--sidebar': '#141416',
      '--surface': '#1A1A1D',
      '--code-bg': '#0C0C0E',
      '--main-bg': '#111113',
      '--border': 'rgba(255,255,255,.075)',
      '--border2': 'rgba(255,255,255,.14)',
      '--border-subtle': 'rgba(255,255,255,.05)',
      '--border-muted': 'rgba(255,255,255,.1)',
      '--surface-subtle': 'rgba(255,255,255,.035)',
      '--surface-subtle-hover': 'rgba(255,255,255,.06)',
      '--input-bg': 'rgba(255,255,255,.04)',
      '--hover-bg': 'rgba(255,255,255,.06)',
      '--topbar-bg': '#0F0F10',
      '--text': '#EDEDEF',
      '--muted': '#8A8A92',
      '--strong': '#FFFFFF',
      '--code-text': '#F5C542',
      '--code-inline-bg': 'rgba(255,255,255,.07)',
      '--pre-text': '#E6E6EB',
      '--user-bubble-bg': '#202023',
      '--user-bubble-border': '#202023',
      '--user-bubble-text': '#F4F4F5',
      '--user-bubble-placeholder': '#8E8E93',
      '--island-ring': 'rgba(255,255,255,.06)',
    },
  },
  {
    key: 'ares',
    name: 'Ares',
    colors: ['#FF4444','#CC3333','#992222'],
    tokens: {
      '--accent': '#C0392B',
      '--accent-hover': '#A93226',
      '--accent-bg': 'rgba(192,57,43,0.08)',
      '--accent-bg-strong': 'rgba(192,57,43,0.15)',
      '--accent-text': '#922B21',
    },
    dark: {
      '--accent': '#FF4444',
      '--accent-hover': '#CC3333',
      '--accent-bg': 'rgba(255,68,68,0.08)',
      '--accent-bg-strong': 'rgba(255,68,68,0.15)',
      '--accent-text': '#FF4444',
    },
  },
  {
    key: 'mono',
    name: 'Mono',
    colors: ['#CCCCCC','#999999','#666666'],
    tokens: {
      '--accent': '#666666',
      '--accent-hover': '#555555',
      '--accent-bg': 'rgba(102,102,102,0.08)',
      '--accent-bg-strong': 'rgba(102,102,102,0.15)',
      '--accent-text': '#555555',
    },
    dark: {
      '--accent': '#CCCCCC',
      '--accent-hover': '#999999',
      '--accent-bg': 'rgba(204,204,204,0.08)',
      '--accent-bg-strong': 'rgba(204,204,204,0.15)',
      '--accent-text': '#CCCCCC',
    },
  },
  {
    key: 'graphite',
    name: 'Graphite',
    colors: ['#FFFFFF','#D6D6D6','#242424'],
    traits: ['card-sessions'],
    tokens: {
      '--bg': '#FFFFFF',
      '--sidebar': '#F3F3F3',
      '--surface': '#FFFFFF',
      '--surface-subtle': '#F7F7F7',
      '--surface-subtle-hover': '#EFEFEF',
      '--border': '#E2E2E2',
      '--border2': '#CFCFCF',
      '--border-subtle': '#E8E8E8',
      '--border-muted': '#D6D6D6',
      '--text': '#242424',
      '--strong': '#111111',
      '--muted': '#707070',
      '--em': '#4F4F4F',
      '--accent': '#303030',
      '--accent-hover': '#171717',
      '--accent-bg': 'rgba(0,0,0,0.07)',
      '--accent-bg-strong': 'rgba(0,0,0,0.13)',
      '--accent-text': '#303030',
      '--blue': '#5F5F5F',
      '--gold': '#303030',
      '--focus-ring': 'rgba(0,0,0,0.18)',
      '--focus-glow': 'rgba(0,0,0,0.06)',
      '--input-bg': '#FFFFFF',
      '--hover-bg': 'rgba(0,0,0,0.05)',
      '--code-bg': '#F1F1F1',
      '--code-inline-bg': 'rgba(0,0,0,0.06)',
      '--code-text': '#242424',
      '--pre-text': '#242424',
      '--topbar-bg': 'rgba(255,255,255,0.94)',
      '--main-bg': '#FFFFFF',
      '--error': '#D44D4D',
      '--success': '#0F8F70',
      '--warning': '#B87916',
      '--info': '#55564F',
      '--user-bubble-bg': '#EFEFEF',
      '--user-bubble-border': '#DEDEDE',
      '--user-bubble-text': '#242424',
      '--user-bubble-placeholder': '#707070',
      '--user-selection-bg': 'rgba(0,0,0,0.16)',
      '--user-selection-text': '#111111',
      '--font-ui': '-apple-system,BlinkMacSystemFont,\"Segoe UI\",sans-serif',
      '--body-weight': '430',
      '--body-tracking': '0',
      '--text-rendering': 'optimizeLegibility',
      '--body-bg': 'var(--bg)',
      '--canvas': 'var(--sidebar)',
      '--rail-bg': 'var(--sidebar)',
      '--titlebar-bg': 'var(--sidebar)',
      '--sidebar-border': 'var(--border)',
      '--pane-bg': 'var(--bg)',
      '--composer-wrap-bg': 'var(--sidebar)',
      '--composer-bg': 'var(--surface)',
      '--composer-border-color': 'var(--border2)',
      '--composer-radius': '14px',
      '--composer-shadow': '0 1px 2px rgba(0,0,0,.07)',
      '--composer-focus-border': 'var(--accent)',
      '--composer-focus-shadow': '0 0 0 2px var(--focus-ring)',
      '--composer-font-size': '14px',
      '--composer-line-height': '1.45',
      '--composer-tracking': '0',
      '--msg-tracking': '0',
      '--msg-code-size': '.92em',
      '--link-color': 'var(--accent-text)',
      '--user-msg-bg': 'var(--user-bubble-bg)', '--user-msg-weight': 'var(--body-weight)', '--user-msg-size': 'var(--message-body-font-size)', '--user-msg-padding': '8px 12px',
      '--user-msg-rail': 'var(--user-bubble-border)',
      '--user-msg-radius': '12px',
      '--user-msg-fg': 'var(--user-bubble-text)',
      '--scroll-btn-bg': 'var(--surface)',
      '--scroll-btn-shadow': '0 1px 2px rgba(0,0,0,.08)',
      '--float-shadow': '0 1px 2px rgba(0,0,0,.08)',
      '--send-weight': '600',
      '--session-radius': '8px',
      '--session-font-size': '12.5px',
      '--session-line-height': '1.42',
      '--session-active-bg': 'var(--surface-subtle-hover)',
      '--session-active-fg': 'var(--text)',
      '--session-active-border': '1px solid var(--border)',
      '--session-active-rail-width': '1px',
      '--session-active-rail-color': 'var(--border)',
      '--session-active-title-fg': 'inherit',
      '--session-active-meta-fg': 'inherit',
      '--session-bar-color': 'color-mix(in srgb,var(--accent) 70%,var(--border2))',
      '--session-bar-radius': '999px',
      '--session-bar-inset-y': '12px',
      '--session-bar-left': '7px',
      '--session-bar-opacity': '.55',
      '--pick-active-bg': 'var(--surface)',
      '--pick-active-border': 'var(--border2)',
      '--pick-active-shadow': 'inset 0 0 0 1px var(--accent)',
      '--heading-tracking': '0',
      '--titlebar-title-tracking': '0',
      '--tool-running-bg': 'var(--accent-bg)',
      '--tool-running-border': 'var(--accent-bg-strong)',
    },
    dark: {
      '--bg': '#151614',
      '--sidebar': '#242624',
      '--surface': '#1B1C1A',
      '--surface-subtle': '#20211F',
      '--surface-subtle-hover': '#292B28',
      '--border': '#343631',
      '--border2': '#4B4D47',
      '--border-subtle': '#2A2C28',
      '--border-muted': '#3D3F3A',
      '--text': '#ECEBE4',
      '--strong': '#FAF9F3',
      '--muted': '#A7A79D',
      '--em': '#D7D6CE',
      '--accent': '#D7D6CE',
      '--accent-hover': '#F4F3EC',
      '--accent-bg': 'rgba(255,255,255,0.08)',
      '--accent-bg-strong': 'rgba(255,255,255,0.14)',
      '--accent-text': '#D7D6CE',
      '--blue': '#C9C8C0',
      '--gold': '#D7D6CE',
      '--focus-ring': 'rgba(244,243,236,0.22)',
      '--focus-glow': 'rgba(244,243,236,0.08)',
      '--input-bg': '#1E1F1D',
      '--hover-bg': 'rgba(255,255,255,0.06)',
      '--code-bg': '#111210',
      '--code-inline-bg': 'rgba(255,255,255,0.08)',
      '--code-text': '#F1F0EA',
      '--pre-text': '#ECEBE4',
      '--topbar-bg': 'rgba(21,22,20,0.92)',
      '--main-bg': '#151614',
      '--error': '#FF6B6B',
      '--success': '#10A37F',
      '--warning': '#E6B15C',
      '--info': '#C9C8C0',
      '--user-bubble-bg': '#2E302D',
      '--user-bubble-border': '#454741',
      '--user-bubble-text': '#F4F3EC',
      '--user-bubble-placeholder': '#A7A79D',
      '--user-selection-bg': 'rgba(255,255,255,0.18)',
      '--user-selection-text': '#FAF9F3',
      '--accent-fg': '#151614',
      '--composer-shadow': '0 1px 2px rgba(0,0,0,.28)',
      '--scroll-btn-shadow': '0 1px 2px rgba(0,0,0,.28)',
      '--float-shadow': '0 1px 2px rgba(0,0,0,.28)',
    },
  },
  {
    key: 'github',
    name: 'GitHub',
    colors: ['#0969DA','#1F883D','#242424'],
    traits: ['card-sessions'],
    tokens: {
      '--bg': '#FFFFFF',
      '--sidebar': '#F3F3F3',
      '--surface': '#FFFFFF',
      '--surface-subtle': '#F7F7F7',
      '--surface-subtle-hover': '#EFEFEF',
      '--border': '#E2E2E2',
      '--border2': '#CFCFCF',
      '--border-subtle': '#E8E8E8',
      '--border-muted': '#D6D6D6',
      '--text': '#242424',
      '--strong': '#111111',
      '--muted': '#707070',
      '--em': '#4F4F4F',
      '--accent': '#0969DA',
      '--accent-hover': '#0550AE',
      '--accent-bg': '#DDF4FF',
      '--accent-bg-strong': 'rgba(9,105,218,0.18)',
      '--accent-text': '#0969DA',
      '--blue': '#0969DA',
      '--gold': '#0969DA',
      '--focus-ring': 'rgba(9,105,218,0.30)',
      '--focus-glow': 'rgba(9,105,218,0.10)',
      '--input-bg': '#FFFFFF',
      '--hover-bg': 'rgba(0,0,0,0.05)',
      '--code-bg': '#F1F1F1',
      '--code-inline-bg': 'rgba(0,0,0,0.06)',
      '--code-text': '#242424',
      '--pre-text': '#242424',
      '--topbar-bg': 'rgba(255,255,255,0.94)',
      '--main-bg': '#FFFFFF',
      '--error': '#D1242F',
      '--success': '#1A7F37',
      '--warning': '#9A6700',
      '--info': '#0969DA',
      '--user-bubble-bg': '#EFEFEF',
      '--user-bubble-border': '#DEDEDE',
      '--user-bubble-text': '#242424',
      '--user-bubble-placeholder': '#707070',
      '--user-selection-bg': 'rgba(0,0,0,0.16)',
      '--user-selection-text': '#111111',
      '--font-ui': '-apple-system,BlinkMacSystemFont,\"Segoe UI\",sans-serif',
      '--body-weight': '430',
      '--body-tracking': '0',
      '--text-rendering': 'optimizeLegibility',
      '--body-bg': 'var(--bg)',
      '--canvas': 'var(--sidebar)',
      '--rail-bg': 'var(--sidebar)',
      '--titlebar-bg': 'var(--sidebar)',
      '--sidebar-border': 'var(--border)',
      '--pane-bg': 'var(--bg)',
      '--composer-wrap-bg': 'var(--sidebar)',
      '--composer-bg': 'var(--surface)',
      '--composer-border-color': 'var(--border2)',
      '--composer-radius': '14px',
      '--composer-shadow': '0 1px 2px rgba(0,0,0,.07)',
      '--composer-focus-border': 'var(--accent)',
      '--composer-focus-shadow': '0 0 0 2px var(--focus-ring)',
      '--composer-font-size': '14px',
      '--composer-line-height': '1.45',
      '--composer-tracking': '0',
      '--msg-tracking': '0',
      '--msg-code-size': '.92em',
      '--link-color': 'var(--accent-text)',
      '--user-msg-bg': 'var(--user-bubble-bg)', '--user-msg-weight': 'var(--body-weight)', '--user-msg-size': 'var(--message-body-font-size)', '--user-msg-padding': '8px 12px',
      '--user-msg-rail': 'var(--user-bubble-border)',
      '--user-msg-radius': '12px',
      '--user-msg-fg': 'var(--user-bubble-text)',
      '--scroll-btn-bg': 'var(--surface)',
      '--scroll-btn-shadow': '0 1px 2px rgba(0,0,0,.08)',
      '--float-shadow': '0 1px 2px rgba(0,0,0,.08)',
      '--send-weight': '600',
      '--session-radius': '8px',
      '--session-font-size': '12.5px',
      '--session-line-height': '1.42',
      '--session-active-bg': 'var(--surface-subtle-hover)',
      '--session-active-fg': 'var(--text)',
      '--session-active-border': '1px solid var(--border)',
      '--session-active-rail-width': '1px',
      '--session-active-rail-color': 'var(--border)',
      '--session-active-title-fg': 'inherit',
      '--session-active-meta-fg': 'inherit',
      '--session-bar-color': 'color-mix(in srgb,var(--accent) 70%,var(--border2))',
      '--session-bar-radius': '999px',
      '--session-bar-inset-y': '12px',
      '--session-bar-left': '7px',
      '--session-bar-opacity': '.55',
      '--pick-active-bg': 'var(--surface)',
      '--pick-active-border': 'var(--border2)',
      '--pick-active-shadow': 'inset 0 0 0 1px var(--accent)',
      '--heading-tracking': '0',
      '--titlebar-title-tracking': '0',
      '--tool-running-bg': 'var(--accent-bg)',
      '--tool-running-border': 'var(--accent-bg-strong)',
    },
    dark: {
      '--bg': '#151614',
      '--sidebar': '#242624',
      '--surface': '#1B1C1A',
      '--surface-subtle': '#20211F',
      '--surface-subtle-hover': '#292B28',
      '--border': '#343631',
      '--border2': '#4B4D47',
      '--border-subtle': '#2A2C28',
      '--border-muted': '#3D3F3A',
      '--text': '#ECEBE4',
      '--strong': '#FAF9F3',
      '--muted': '#A7A79D',
      '--em': '#D7D6CE',
      '--accent': '#4493F8',
      '--accent-hover': '#58A6FF',
      '--accent-bg': 'rgba(56,139,253,0.10)',
      '--accent-bg-strong': 'rgba(31,111,235,0.24)',
      '--accent-text': '#58A6FF',
      '--blue': '#58A6FF',
      '--gold': '#4493F8',
      '--focus-ring': 'rgba(31,111,235,0.34)',
      '--focus-glow': 'rgba(31,111,235,0.12)',
      '--input-bg': '#1E1F1D',
      '--hover-bg': 'rgba(255,255,255,0.06)',
      '--code-bg': '#111210',
      '--code-inline-bg': 'rgba(255,255,255,0.08)',
      '--code-text': '#F1F0EA',
      '--pre-text': '#ECEBE4',
      '--topbar-bg': 'rgba(21,22,20,0.92)',
      '--main-bg': '#151614',
      '--error': '#FF7B72',
      '--success': '#3FB950',
      '--warning': '#D29922',
      '--info': '#58A6FF',
      '--user-bubble-bg': '#2E302D',
      '--user-bubble-border': '#454741',
      '--user-bubble-text': '#F4F3EC',
      '--user-bubble-placeholder': '#A7A79D',
      '--user-selection-bg': 'rgba(255,255,255,0.18)',
      '--user-selection-text': '#FAF9F3',
      '--accent-fg': '#151614',
      '--composer-shadow': '0 1px 2px rgba(0,0,0,.28)',
      '--scroll-btn-shadow': '0 1px 2px rgba(0,0,0,.28)',
      '--float-shadow': '0 1px 2px rgba(0,0,0,.28)',
    },
  },
  {
    key: 'slate',
    name: 'Slate',
    colors: ['#334155','#475569','#64748b'],
    tokens: {
      '--accent': '#475569',
      '--accent-hover': '#334155',
      '--accent-bg': 'rgba(71,85,105,0.08)',
      '--accent-bg-strong': 'rgba(71,85,105,0.15)',
      '--accent-text': '#334155',
    },
    dark: {
      '--accent': '#94A3B8',
      '--accent-hover': '#64748B',
      '--accent-bg': 'rgba(148,163,184,0.08)',
      '--accent-bg-strong': 'rgba(148,163,184,0.15)',
      '--accent-text': '#94A3B8',
    },
  },
  {
    key: 'poseidon',
    name: 'Poseidon',
    colors: ['#0EA5E9','#0284C7','#0369A1'],
    tokens: {
      '--accent': '#0369A1',
      '--accent-hover': '#025080',
      '--accent-bg': 'rgba(3,105,161,0.08)',
      '--accent-bg-strong': 'rgba(3,105,161,0.15)',
      '--accent-text': '#025080',
    },
    dark: {
      '--accent': '#0EA5E9',
      '--accent-hover': '#0284C7',
      '--accent-bg': 'rgba(14,165,233,0.08)',
      '--accent-bg-strong': 'rgba(14,165,233,0.15)',
      '--accent-text': '#0EA5E9',
    },
  },
  {
    key: 'sisyphus',
    name: 'Sisyphus',
    colors: ['#A78BFA','#8B5CF6','#7C3AED'],
    tokens: {
      '--accent': '#7C3AED',
      '--accent-hover': '#6D28D9',
      '--accent-bg': 'rgba(124,58,237,0.08)',
      '--accent-bg-strong': 'rgba(124,58,237,0.15)',
      '--accent-text': '#6D28D9',
    },
    dark: {
      '--accent': '#A78BFA',
      '--accent-hover': '#8B5CF6',
      '--accent-bg': 'rgba(167,139,250,0.08)',
      '--accent-bg-strong': 'rgba(167,139,250,0.15)',
      '--accent-text': '#A78BFA',
    },
  },
  {
    key: 'charizard',
    name: 'Charizard',
    colors: ['#FB923C','#F97316','#EA580C'],
    tokens: {
      '--accent': '#EA580C',
      '--accent-hover': '#C2410C',
      '--accent-bg': 'rgba(234,88,12,0.08)',
      '--accent-bg-strong': 'rgba(234,88,12,0.15)',
      '--accent-text': '#C2410C',
    },
    dark: {
      '--accent': '#FB923C',
      '--accent-hover': '#F97316',
      '--accent-bg': 'rgba(251,146,60,0.08)',
      '--accent-bg-strong': 'rgba(251,146,60,0.15)',
      '--accent-text': '#FB923C',
    },
  },
  {
    key: 'sienna',
    name: 'Sienna',
    colors: ['#D97757','#C06A49','#9A523A'],
    tokens: {
      '--bg': '#FAF9F5',
      '--sidebar': '#F0EEE6',
      '--surface': '#FFFFFF',
      '--border': '#E7E4DB',
      '--border2': '#D7D3C7',
      '--text': '#1F1E1C',
      '--muted': '#6B6A63',
      '--strong': '#141311',
      '--em': '#3E3D39',
      '--accent': '#D97757',
      '--accent-hover': '#BF6545',
      '--accent-text': '#A55237',
      '--accent-bg': 'rgba(217,119,87,0.09)',
      '--accent-bg-strong': 'rgba(217,119,87,0.18)',
      '--code-bg': '#F5F3EC',
      '--code-inline-bg': 'rgba(20,19,17,0.06)',
      '--code-text': '#8A3E1A',
      '--pre-text': '#1F1E1C',
      '--topbar-bg': 'rgba(250,249,245,0.96)',
      '--main-bg': 'rgba(250,249,245,0.55)',
      '--input-bg': 'rgba(20,19,17,0.035)',
      '--hover-bg': 'rgba(20,19,17,0.05)',
      '--focus-ring': 'rgba(217,119,87,0.3)',
      '--focus-glow': 'rgba(217,119,87,0.1)',
      '--blue': '#2E6F9E',
      '--gold': '#A55237',
      '--user-bubble-bg': '#ECE9DF',
      '--user-bubble-border': '#DED9CC',
      '--user-bubble-text': '#1F1E1C',
      '--user-bubble-placeholder': '#6B6A63',
      '--user-selection-bg': 'rgba(217,119,87,0.28)',
      '--user-selection-text': '#1F1E1C',
      '--user-msg-radius': '16px',
      '--user-msg-padding': '12px 16px',
      '--user-msg-code-bg': 'rgba(20,19,17,.08)',
      '--composer-radius': '18px',
      '--session-active-rail-width': '2px',
      '--session-active-rail-color': 'var(--accent)',
      '--send-shadow': '0 1px 3px color-mix(in srgb,var(--accent-hover) 30%,transparent)',
      '--send-hover-shadow': '0 2px 8px color-mix(in srgb,var(--accent-hover) 45%,transparent)',
      '--tool-running-bg': 'var(--accent-bg)',
      '--tool-running-border': 'var(--accent-bg-strong)',
    },
    dark: {
      '--bg': '#1F1E1C',
      '--sidebar': '#262522',
      '--surface': '#2C2B28',
      '--border': '#3A3935',
      '--border2': '#4A4843',
      '--text': '#EDEBE3',
      '--muted': '#A3A197',
      '--strong': '#F7F5ED',
      '--em': '#C9C6BC',
      '--accent': '#E0896D',
      '--accent-hover': '#D97757',
      '--accent-text': '#E6A88A',
      '--accent-bg': 'rgba(224,137,109,0.12)',
      '--accent-bg-strong': 'rgba(224,137,109,0.22)',
      '--code-bg': '#2A2926',
      '--code-inline-bg': 'rgba(255,255,255,0.07)',
      '--code-text': '#F0B593',
      '--pre-text': '#EDEBE3',
      '--topbar-bg': 'rgba(38,37,34,0.96)',
      '--main-bg': 'rgba(31,30,28,0.55)',
      '--input-bg': 'rgba(255,255,255,0.045)',
      '--hover-bg': 'rgba(255,255,255,0.07)',
      '--focus-ring': 'rgba(224,137,109,0.35)',
      '--focus-glow': 'rgba(224,137,109,0.1)',
      '--blue': '#8BB8D6',
      '--gold': '#E6A88A',
      '--user-bubble-bg': '#34322E',
      '--user-bubble-border': '#42403B',
      '--user-bubble-text': '#EDEBE3',
      '--user-bubble-placeholder': '#A3A197',
      '--user-selection-bg': 'rgba(224,137,109,0.3)',
      '--user-selection-text': '#F7F5ED',
    },
  },
  {
    key: 'catppuccin',
    name: 'Catppuccin',
    colors: ['#CBA6F7','#B4BEFE','#8839EF'],
    tokens: {
      '--bg': '#EFF1F5',
      '--sidebar': '#E6E9EF',
      '--surface': '#FFFFFF',
      '--border': '#CCD0DA',
      '--border2': '#BCC0CC',
      '--text': '#4C4F69',
      '--muted': '#7C7F93',
      '--strong': '#1E1E2E',
      '--em': '#5C5F77',
      '--accent': '#8839EF',
      '--accent-hover': '#6C26D6',
      '--accent-text': '#8839EF',
      '--accent-bg': 'rgba(136,57,239,0.09)',
      '--accent-bg-strong': 'rgba(136,57,239,0.18)',
      '--code-bg': '#E6E9EF',
      '--code-inline-bg': 'rgba(30,30,46,0.06)',
      '--code-text': '#8839EF',
      '--pre-text': '#4C4F69',
      '--topbar-bg': 'rgba(239,241,245,0.96)',
      '--main-bg': 'rgba(239,241,245,0.55)',
      '--input-bg': 'rgba(30,30,46,0.035)',
      '--hover-bg': 'rgba(30,30,46,0.05)',
      '--focus-ring': 'rgba(136,57,239,0.3)',
      '--focus-glow': 'rgba(136,57,239,0.1)',
      '--blue': '#1E66F5',
      '--gold': '#DF8E1D',
      '--user-bubble-bg': '#E6E9EF',
      '--user-bubble-border': '#CCD0DA',
      '--user-bubble-text': '#4C4F69',
      '--user-bubble-placeholder': '#7C7F93',
      '--user-selection-bg': 'rgba(136,57,239,0.24)',
      '--user-selection-text': '#1E1E2E',
      '--tool-running-bg': 'var(--accent-bg)',
      '--tool-running-border': 'var(--accent-bg-strong)',
    },
    dark: {
      '--bg': '#1E1E2E',
      '--sidebar': '#181825',
      '--surface': '#313244',
      '--border': '#45475A',
      '--border2': '#585B70',
      '--text': '#CDD6F4',
      '--muted': '#A6ADC8',
      '--strong': '#F5F5F5',
      '--em': '#BAC2DE',
      '--accent': '#CBA6F7',
      '--accent-hover': '#B4BEFE',
      '--accent-text': '#CBA6F7',
      '--accent-bg': 'rgba(203,166,247,0.12)',
      '--accent-bg-strong': 'rgba(203,166,247,0.22)',
      '--code-bg': '#181825',
      '--code-inline-bg': 'rgba(255,255,255,0.07)',
      '--code-text': '#CBA6F7',
      '--pre-text': '#CDD6F4',
      '--topbar-bg': 'rgba(30,30,46,0.96)',
      '--main-bg': 'rgba(30,30,46,0.55)',
      '--input-bg': 'rgba(255,255,255,0.045)',
      '--hover-bg': 'rgba(255,255,255,0.07)',
      '--focus-ring': 'rgba(203,166,247,0.35)',
      '--focus-glow': 'rgba(203,166,247,0.1)',
      '--blue': '#89B4FA',
      '--gold': '#F9E2AF',
      '--user-bubble-bg': '#313244',
      '--user-bubble-border': '#45475A',
      '--user-bubble-text': '#CDD6F4',
      '--user-bubble-placeholder': '#A6ADC8',
      '--user-selection-bg': 'rgba(203,166,247,0.3)',
      '--user-selection-text': '#1E1E2E',
    },
  },
  {
    key: 'hepburn',
    name: 'Hepburn',
    colors: ['#c6246a','#ec5597','#f2abca'],
    tokens: {
      '--bg': '#fff3f7',
      '--sidebar': '#fbe4ed',
      '--surface': '#fff9fb',
      '--border': '#ecc8d5',
      '--border2': 'rgba(242,120,173,0.18)',
      '--text': '#3d1a28',
      '--muted': '#906270',
      '--strong': '#260912',
      '--em': '#72384a',
      '--accent': '#d44a7a',
      '--accent-hover': '#c6246a',
      '--accent-text': '#c6246a',
      '--accent-bg': 'rgba(242,120,173,0.10)',
      '--accent-bg-strong': 'rgba(242,120,173,0.20)',
      '--code-bg': '#fbe6ef',
      '--code-inline-bg': 'rgba(242,120,173,0.12)',
      '--code-text': '#d44a7a',
      '--pre-text': '#3d1a28',
      '--topbar-bg': 'rgba(251,228,237,0.96)',
      '--main-bg': 'rgba(255,243,247,0.5)',
      '--input-bg': 'rgba(242,120,173,0.06)',
      '--hover-bg': 'rgba(242,120,173,0.08)',
      '--focus-ring': 'rgba(242,120,173,0.35)',
      '--focus-glow': 'rgba(242,120,173,0.12)',
      '--blue': '#8671e5',
      '--gold': '#d44a7a',
      '--error': '#c0392b',
      '--success': '#3d8b40',
      '--warning': '#e67e22',
      '--info': '#8671e5',
      '--surface-subtle': 'rgba(242,120,173,0.04)',
      '--surface-subtle-hover': 'rgba(242,120,173,0.08)',
      '--border-subtle': 'rgba(242,120,173,0.10)',
      '--border-muted': 'rgba(242,120,173,0.16)',
      '--send-bg': 'var(--gold)',
      '--send-fg': '#fff',
      '--send-shadow': '0 1px 3px color-mix(in srgb,var(--gold) 30%,transparent)',
      '--send-hover-bg': '#c6246a',
      '--send-hover-shadow': '0 2px 8px rgba(198,36,106,.45)',
      '--session-active-rail-width': '2px',
      '--session-active-rail-color': 'var(--accent)',
      '--tool-running-bg': 'var(--accent-bg)',
      '--tool-running-border': 'var(--accent-bg-strong)',
    },
    dark: {
      '--bg': '#110a0f',
      '--sidebar': '#1e0f19',
      '--surface': '#241420',
      '--border': '#311a28',
      '--border2': 'rgba(242,120,173,0.20)',
      '--text': '#f2e4ee',
      '--muted': '#c8a4b8',
      '--strong': '#fcf4f8',
      '--em': '#e5c4d8',
      '--accent': '#f278ad',
      '--accent-hover': '#f5a0c5',
      '--accent-text': '#f278ad',
      '--accent-bg': 'rgba(242,120,173,0.14)',
      '--accent-bg-strong': 'rgba(242,120,173,0.25)',
      '--code-bg': '#1e0f19',
      '--code-inline-bg': 'rgba(242,120,173,0.22)',
      '--code-text': '#f5a0c5',
      '--pre-text': '#f2e4ee',
      '--topbar-bg': 'rgba(30,15,25,0.96)',
      '--main-bg': 'rgba(17,10,15,0.5)',
      '--input-bg': 'rgba(242,120,173,0.08)',
      '--hover-bg': 'rgba(242,120,173,0.12)',
      '--focus-ring': 'rgba(242,120,173,0.45)',
      '--focus-glow': 'rgba(242,120,173,0.18)',
      '--blue': '#8671e5',
      '--gold': '#ec5597',
      '--error': '#ff5c5c',
      '--success': '#6cd4a5',
      '--warning': '#f2b370',
      '--info': '#8671e5',
      '--surface-subtle': 'rgba(242,120,173,0.05)',
      '--surface-subtle-hover': 'rgba(242,120,173,0.10)',
      '--border-subtle': 'rgba(242,120,173,0.12)',
      '--border-muted': 'rgba(242,120,173,0.22)',
    },
  },
  {
    key: 'nous',
    name: 'Nous',
    colors: ['#4682B4','#3A6E9A','#2C5F88'],
    tokens: {
      '--bg': '#FFFFFF',
      '--sidebar': '#F5F5F5',
      '--border': '#D0D8E0',
      '--border2': 'rgba(0,0,0,0.15)',
      '--text': '#1A2A3A',
      '--muted': '#6B7B8B',
      '--accent': '#4682B4',
      '--blue': '#4682B4',
      '--gold': '#4682B4',
      '--code-bg': '#F0F2F5',
      '--surface': '#FFFFFF',
      '--topbar-bg': 'rgba(255,255,255,.98)',
      '--main-bg': 'rgba(255,255,255,0.5)',
      '--focus-ring': 'rgba(70,130,180,.3)',
      '--focus-glow': 'rgba(70,130,180,.08)',
      '--input-bg': 'rgba(0,0,0,.03)',
      '--hover-bg': 'rgba(0,0,0,.05)',
      '--strong': '#0A1A2A',
      '--em': '#5C5344',
      '--code-text': '#2C5F88',
      '--code-inline-bg': 'rgba(70,130,180,.08)',
      '--pre-text': '#1A2A3A',
      '--accent-hover': '#3A6E9A',
      '--accent-bg': 'rgba(70,130,180,0.06)',
      '--accent-bg-strong': 'rgba(70,130,180,0.12)',
      '--accent-text': '#2C5F88',
      '--error': '#C62828',
      '--success': '#3D8B40',
      '--warning': '#E68A00',
      '--info': '#4682B4',
      '--radius-sm': '1px',
      '--radius-md': '2px',
      '--radius-card': '2px',
      '--radius-lg': '4px',
      '--font-ui': '\"SF Mono\",\"Roboto Mono\",\"Courier New\",monospace',
      '--surface-subtle': 'rgba(0,0,0,.025)',
      '--surface-subtle-hover': 'rgba(0,0,0,.045)',
      '--border-subtle': 'rgba(0,0,0,.08)',
      '--border-muted': 'rgba(0,0,0,.12)',
      '--sidebar-border-style': 'dashed',
      '--scrollbar-thumb': 'color-mix(in srgb,var(--accent) 25%,transparent)',
      '--scrollbar-thumb-hover': 'color-mix(in srgb,var(--accent) 40%,transparent)',
      '--root-font-size': '14.5px',
      '--root-line-height': '1.7',
    },
    dark: {
      '--bg': '#0A0E14',
      '--sidebar': '#0F1419',
      '--border': '#1E2A3A',
      '--border2': 'rgba(255,255,255,0.14)',
      '--text': '#C8D6E5',
      '--muted': '#5A6A7A',
      '--accent': '#4682B4',
      '--blue': '#4682B4',
      '--gold': '#4682B4',
      '--code-bg': '#111820',
      '--surface': '#111820',
      '--topbar-bg': 'rgba(10,14,20,.98)',
      '--main-bg': 'rgba(10,14,20,0.5)',
      '--focus-ring': 'rgba(70,130,180,.3)',
      '--focus-glow': 'rgba(70,130,180,.08)',
      '--input-bg': 'rgba(255,255,255,.04)',
      '--hover-bg': 'rgba(255,255,255,.06)',
      '--strong': '#E2E8F0',
      '--em': '#5A6A7A',
      '--code-text': '#7EB6E0',
      '--code-inline-bg': 'rgba(70,130,180,.12)',
      '--pre-text': '#C8D6E5',
      '--accent-hover': '#5A9AD0',
      '--accent-bg': 'rgba(70,130,180,0.1)',
      '--accent-bg-strong': 'rgba(70,130,180,0.2)',
      '--accent-text': '#7EB6E0',
      '--error': '#EF5350',
      '--success': '#4CAF50',
      '--warning': '#FFA726',
      '--info': '#4682B4',
      '--surface-subtle': 'rgba(255,255,255,.025)',
      '--surface-subtle-hover': 'rgba(255,255,255,.045)',
      '--border-subtle': 'rgba(255,255,255,.075)',
      '--border-muted': 'rgba(255,255,255,.12)',
    },
  },
  {
    key: 'geist-contrast',
    name: 'Geist Contrast',
    colors: ['#000000','#ffffff','#FFF175'],
    traits: ['square-controls'],
    tokens: {
      '--bg': '#ffffff',
      '--sidebar': '#fafafa',
      '--surface': '#ffffff',
      '--surface-subtle': '#fafafa',
      '--surface-subtle-hover': '#f5f5f5',
      '--main-bg': '#ffffff',
      '--topbar-bg': 'rgba(255,255,255,.92)',
      '--border': '#eaeaea',
      '--border2': '#d4d4d4',
      '--border-subtle': '#ededed',
      '--border-muted': '#d4d4d4',
      '--text': '#111111',
      '--strong': '#000000',
      '--muted': '#666666',
      '--em': '#444444',
      '--accent': '#0070f3',
      '--accent-hover': '#005bd1',
      '--accent-bg': 'rgba(0,112,243,.075)',
      '--accent-bg-strong': 'rgba(0,112,243,.16)',
      '--accent-text': '#005bd1',
      '--blue': '#0070f3',
      '--gold': '#111111',
      '--focus-ring': 'rgba(0,112,243,.28)',
      '--focus-glow': 'rgba(0,112,243,.08)',
      '--input-bg': '#ffffff',
      '--hover-bg': '#f5f5f5',
      '--code-bg': '#fafafa',
      '--code-inline-bg': '#f5f5f5',
      '--code-text': '#111111',
      '--pre-text': '#111111',
      '--error': '#e5484d',
      '--success': '#007a45',
      '--warning': '#b45309',
      '--info': '#0070f3',
      '--radius-sm': '4px',
      '--radius-md': '6px',
      '--radius-card': '8px',
      '--radius-lg': '10px',
      '--font-ui': '\"Geist\",\"Geist Sans\",-apple-system,BlinkMacSystemFont,\"Segoe UI\",Helvetica,Arial,sans-serif',
      '--user-bubble-text': '#111111',
      '--accent-fg': '#ffffff',
      '--body-bg': 'var(--bg)',
      '--canvas': 'var(--sidebar)',
      '--body-tracking': '-0.011em',
      '--rail-bg': 'var(--sidebar)',
      '--titlebar-bg': 'var(--sidebar)',
      '--sidebar-border': 'var(--border)',
      '--chrome-backdrop': 'saturate(180%) blur(12px)',
      '--main-surface': 'var(--surface)',
      '--island-ring-width': '0',
      '--pane-bg': 'var(--surface)',
      '--composer-wrap-bg': 'var(--sidebar)',
      '--composer-bg': 'var(--surface)',
      '--composer-border-width': '0',
      '--composer-shadow': 'none',
      '--composer-focus-border': 'transparent',
      '--composer-focus-shadow': '0 0 0 3px var(--focus-ring)',
      '--composer-scrollbar-width': 'none',
      '--composer-scrollbar-display': 'none',
      '--link-color': 'var(--accent-text)',
      '--pre-bg': 'var(--surface)',
      '--pre-border': 'none',
      '--user-msg-bg': 'var(--surface-subtle)', '--user-msg-weight': '400', '--user-msg-size': 'var(--message-body-font-size)', '--user-msg-padding': '8px 12px',
      '--user-msg-border': '1px solid var(--border)',
      '--user-msg-rail-width': '1px',
      '--user-msg-rail': 'var(--border)',
      '--user-msg-radius': '10px',
      '--chip-bg': 'transparent',
      '--chip-border': 'transparent',
      '--chip-hover-bg': 'var(--surface-subtle)',
      '--chip-hover-border': 'var(--border)',
      '--ws-chip-hover-bg': 'var(--surface-subtle)',
      '--ws-chip-hover-border': 'var(--border)',
      '--ws-chip-hover-fg': 'var(--text)',
      '--send-weight': '600',
      '--send-disabled-bg': 'var(--surface-subtle)',
      '--send-disabled-opacity': '1',
      '--primary-bg': 'var(--accent)',
      '--primary-fg': 'var(--accent-fg)',
      '--primary-hover-bg': 'var(--accent-hover)',
      '--primary-hover-border': 'var(--accent-hover)',
      '--primary-hover-transform': 'none',
      '--primary-hover-shadow': 'none',
      '--session-radius': '6px',
      '--session-active-bg': 'var(--surface-subtle)',
      '--session-active-fg': 'var(--text)',
      '--session-active-border': '1px solid var(--border2)',
      '--session-active-rail-width': '1px',
      '--session-active-rail-color': 'var(--border2)',
      '--session-active-shadow': 'inset 0 0 0 1px var(--border)',
      '--session-active-weight': '500',
      '--session-active-title-fg': 'inherit',
      '--session-active-meta-fg': 'inherit',
      '--session-bar-radius': '999px',
      '--session-bar-inset-y': '10px',
      '--session-bar-left': '6px',
      '--project-chip-hover-bg': 'var(--hover-bg)',
      '--chip-radius': '6px',
      '--project-chip-active-bg': 'var(--surface-subtle)',
      '--project-chip-active-fg': 'var(--text)',
      '--project-chip-active-border': 'var(--border2)',
      '--project-chip-active-shadow': 'inset 0 0 0 1px var(--border)',
      '--project-chip-active-weight': '500',
      '--pick-active-bg': 'var(--surface-subtle)',
      '--pick-active-border': 'var(--border2)',
      '--pick-active-shadow': 'inset 0 0 0 1px var(--border)',
      '--pick-active-fg': 'var(--text)',
      '--pick-active-weight': '500',
      '--settings-section-bg': 'var(--surface)',
      '--menu-active-bg': 'var(--surface-subtle)',
      '--menu-active-fg': 'var(--text)',
      '--menu-active-shadow': 'inset 0 0 0 1px var(--border)',
      '--menu-active-weight': '500',
      '--btn-radius': '6px',
      '--rail-btn-radius': '6px',
      '--nav-tab-radius': '6px',
      '--nav-tab-radius-mobile': '6px',
      '--input-radius': '6px',
      '--nav-active-bg': 'var(--surface-subtle)',
      '--nav-active-shadow': 'inset 0 0 0 1px var(--border)',
      '--nav-active-weight': '500',
      '--nav-hover-bg': 'var(--hover-bg)',
      '--rail-active-bg': 'var(--surface-subtle)',
      '--rail-active-shadow': 'inset 0 0 0 1px var(--border)',
      '--rail-active-weight': '500',
      '--panel-btn-hover-bg': 'var(--hover-bg)',
      '--icon-btn-hover-bg': 'var(--hover-bg)',
      '--file-item-hover-bg': 'var(--hover-bg)',
      '--input-focus-shadow': 'none',
      '--search-focus-shadow': '0 0 0 3px var(--focus-ring)',
      '--selection-bg': 'var(--accent-bg-strong)',
      '--selection-fg': 'var(--strong)',
      '--scrollbar-thumb': 'var(--border2)',
    },
    dark: {
      '--bg': '#000000',
      '--sidebar': '#050505',
      '--surface': '#0a0a0a',
      '--surface-subtle': '#111111',
      '--surface-subtle-hover': '#171717',
      '--main-bg': '#000000',
      '--topbar-bg': 'rgba(0,0,0,.88)',
      '--border': '#262626',
      '--border2': '#3f3f3f',
      '--border-subtle': '#171717',
      '--border-muted': '#2a2a2a',
      '--text': '#ededed',
      '--strong': '#ffffff',
      '--muted': '#a1a1a1',
      '--em': '#d4d4d4',
      '--accent': '#FFF175',
      '--accent-hover': '#fff7a8',
      '--accent-bg': 'rgba(255,241,117,.075)',
      '--accent-bg-strong': 'rgba(255,241,117,.14)',
      '--accent-text': '#f5e65f',
      '--blue': '#FFF175',
      '--gold': '#FFF175',
      '--focus-ring': 'rgba(255,241,117,.34)',
      '--focus-glow': 'rgba(255,241,117,.10)',
      '--input-bg': '#0a0a0a',
      '--hover-bg': '#111111',
      '--code-bg': '#0a0a0a',
      '--code-inline-bg': '#171717',
      '--code-text': '#f5f5f5',
      '--pre-text': '#ededed',
      '--error': '#ff6369',
      '--success': '#3dd68c',
      '--warning': '#f5a524',
      '--info': '#FFF175',
      '--accent-fg': '#050505',
      '--user-bubble-text': 'var(--text)',
      '--session-active-title-fg': 'var(--text)',
      '--session-active-meta-fg': 'var(--text)',
      '--nav-active-icon-fg': 'var(--accent-text)',
      '--rail-active-icon-fg': 'var(--accent-text)',
    },
  },
  {
    key: 'neon',
    name: 'Neon',
    colors: ['#B347FF','#C76BFF','#00DDFF'],
    tokens: {
      '--bg': '#F8F7FC',
      '--sidebar': '#F0EEF8',
      '--border': '#D8D4EC',
      '--border2': 'rgba(0,0,0,0.12)',
      '--text': '#1E1B2E',
      '--muted': '#6E6888',
      '--accent': '#9333EA',
      '--blue': '#7C3AED',
      '--gold': '#A855F7',
      '--code-bg': '#F0EDF8',
      '--surface': '#FFFFFF',
      '--topbar-bg': 'rgba(248,247,252,.98)',
      '--main-bg': 'rgba(248,247,252,0.5)',
      '--focus-ring': 'rgba(147,51,234,.3)',
      '--focus-glow': 'rgba(147,51,234,.08)',
      '--input-bg': 'rgba(147,51,234,.03)',
      '--hover-bg': 'rgba(147,51,234,.05)',
      '--strong': '#0D0B14',
      '--em': '#7C3AED',
      '--code-text': '#6D28D9',
      '--code-inline-bg': 'rgba(147,51,234,.08)',
      '--pre-text': '#1E1B2E',
      '--accent-hover': '#7E22CE',
      '--accent-bg': 'rgba(147,51,234,0.06)',
      '--accent-bg-strong': 'rgba(147,51,234,0.12)',
      '--accent-text': '#6D28D9',
      '--error': '#DC2626',
      '--success': '#059669',
      '--warning': '#D97706',
      '--info': '#7C3AED',
      '--radius-sm': '2px',
      '--radius-md': '4px',
      '--radius-card': '4px',
      '--radius-lg': '6px',
      '--font-ui': 'system-ui,-apple-system,sans-serif',
      '--surface-subtle': 'rgba(147,51,234,.025)',
      '--surface-subtle-hover': 'rgba(147,51,234,.05)',
      '--border-subtle': 'rgba(147,51,234,.08)',
      '--border-muted': 'rgba(147,51,234,.12)',
      '--purple': '#9333EA',
    },
    dark: {
      '--bg': '#08060d',
      '--sidebar': '#06040a',
      '--border': '#1c1633',
      '--border2': 'rgba(179,71,255,0.15)',
      '--text': '#d8d6f0',
      '--muted': '#6a6588',
      '--accent': '#b347ff',
      '--blue': '#a78bfa',
      '--gold': '#c084fc',
      '--code-bg': '#050308',
      '--surface': '#0f0d1a',
      '--topbar-bg': 'rgba(8,6,13,.98)',
      '--main-bg': 'rgba(8,6,13,0.5)',
      '--focus-ring': 'rgba(179,71,255,.35)',
      '--focus-glow': 'rgba(179,71,255,.10)',
      '--input-bg': 'rgba(179,71,255,.04)',
      '--hover-bg': 'rgba(179,71,255,.06)',
      '--strong': '#f0edff',
      '--em': '#00ddff',
      '--code-text': '#c8c0f0',
      '--code-inline-bg': 'rgba(179,71,255,.10)',
      '--pre-text': '#d8d6f0',
      '--accent-hover': '#c76bff',
      '--accent-bg': 'rgba(179,71,255,0.10)',
      '--accent-bg-strong': 'rgba(179,71,255,0.20)',
      '--accent-text': '#c8a0ff',
      '--error': '#ff4466',
      '--success': '#00dd88',
      '--warning': '#ffaa33',
      '--info': '#00ddff',
      '--surface-subtle': 'rgba(179,71,255,.03)',
      '--surface-subtle-hover': 'rgba(179,71,255,.06)',
      '--border-subtle': 'rgba(179,71,255,.08)',
      '--border-muted': 'rgba(179,71,255,.12)',
      '--purple': '#b347ff',
      '--selection-bg': 'color-mix(in srgb,var(--accent) 35%,transparent)',
      '--selection-fg': '#fff',
      '--titlebar-border': 'color-mix(in srgb,var(--accent) 20%,transparent)',
      '--sidebar-shadow': 'inset -1px 0 30px color-mix(in srgb,var(--accent) 3%,transparent)',
      '--input-focus-shadow': '0 0 16px color-mix(in srgb,var(--accent) 20%,transparent)',
      '--send-shadow': '0 0 14px color-mix(in srgb,var(--accent) 25%,transparent)',
      '--send-hover-shadow': '0 0 24px color-mix(in srgb,var(--accent) 45%,transparent)',
      '--tool-running-bg': 'var(--accent-bg)',
      '--tool-running-border': 'var(--accent-bg-strong)',
      '--link-hover-glow': '0 0 8px rgba(0,221,255,.4)',
      '--scrollbar-thumb': 'color-mix(in srgb,var(--accent) 18%,transparent)',
      '--scrollbar-thumb-hover': 'color-mix(in srgb,var(--accent) 30%,transparent)',
    },
  },
  {
    key: 'neon-soft',
    name: 'Neon Soft',
    colors: ['#B347FF','#C76BFF','#00DDFF'],
    tokens: {
      '--bg': '#F8F7FC',
      '--sidebar': '#F0EEF8',
      '--border': '#D8D4EC',
      '--border2': 'rgba(0,0,0,0.12)',
      '--text': '#1E1B2E',
      '--muted': '#6E6888',
      '--accent': '#9333EA',
      '--blue': '#7C3AED',
      '--gold': '#A855F7',
      '--code-bg': '#F0EDF8',
      '--surface': '#FFFFFF',
      '--topbar-bg': 'rgba(248,247,252,.98)',
      '--main-bg': 'rgba(248,247,252,0.5)',
      '--focus-ring': 'rgba(147,51,234,.3)',
      '--focus-glow': 'rgba(147,51,234,.08)',
      '--input-bg': 'rgba(147,51,234,.03)',
      '--hover-bg': 'rgba(147,51,234,.05)',
      '--strong': '#0D0B14',
      '--em': '#7C3AED',
      '--code-text': '#6D28D9',
      '--code-inline-bg': 'rgba(147,51,234,.08)',
      '--pre-text': '#1E1B2E',
      '--accent-hover': '#7E22CE',
      '--accent-bg': 'rgba(147,51,234,0.06)',
      '--accent-bg-strong': 'rgba(147,51,234,0.12)',
      '--accent-text': '#6D28D9',
      '--error': '#DC2626',
      '--success': '#059669',
      '--warning': '#D97706',
      '--info': '#7C3AED',
      '--radius-sm': '2px',
      '--radius-md': '4px',
      '--radius-card': '4px',
      '--radius-lg': '6px',
      '--font-ui': 'system-ui,-apple-system,sans-serif',
      '--surface-subtle': 'rgba(147,51,234,.025)',
      '--surface-subtle-hover': 'rgba(147,51,234,.05)',
      '--border-subtle': 'rgba(147,51,234,.08)',
      '--border-muted': 'rgba(147,51,234,.12)',
      '--purple': '#9333EA',
    },
    dark: {
      '--bg': '#181428',
      '--sidebar': '#141024',
      '--border': '#2a2448',
      '--border2': 'rgba(179,71,255,0.15)',
      '--text': '#e8e6f8',
      '--muted': '#8a85aa',
      '--accent': '#b347ff',
      '--blue': '#a78bfa',
      '--gold': '#c084fc',
      '--code-bg': '#121020',
      '--surface': '#1c1732',
      '--topbar-bg': 'rgba(24,20,40,.98)',
      '--main-bg': 'rgba(24,20,40,0.5)',
      '--focus-ring': 'rgba(179,71,255,.35)',
      '--focus-glow': 'rgba(179,71,255,.10)',
      '--input-bg': 'rgba(179,71,255,.04)',
      '--hover-bg': 'rgba(179,71,255,.06)',
      '--strong': '#f8f6ff',
      '--em': '#00ddff',
      '--code-text': '#c8c0f0',
      '--code-inline-bg': 'rgba(179,71,255,.10)',
      '--pre-text': '#e8e6f8',
      '--accent-hover': '#c76bff',
      '--accent-bg': 'rgba(179,71,255,0.10)',
      '--accent-bg-strong': 'rgba(179,71,255,0.20)',
      '--accent-text': '#c8a0ff',
      '--error': '#ff4466',
      '--success': '#00dd88',
      '--warning': '#ffaa33',
      '--info': '#00ddff',
      '--surface-subtle': 'rgba(179,71,255,.03)',
      '--surface-subtle-hover': 'rgba(179,71,255,.06)',
      '--border-subtle': 'rgba(179,71,255,.08)',
      '--border-muted': 'rgba(179,71,255,.12)',
      '--purple': '#b347ff',
      '--selection-bg': 'color-mix(in srgb,var(--accent) 35%,transparent)',
      '--selection-fg': '#fff',
      '--titlebar-border': 'color-mix(in srgb,var(--accent) 20%,transparent)',
      '--sidebar-shadow': 'inset -1px 0 30px color-mix(in srgb,var(--accent) 3%,transparent)',
      '--input-focus-shadow': '0 0 16px color-mix(in srgb,var(--accent) 20%,transparent)',
      '--send-shadow': '0 0 14px color-mix(in srgb,var(--accent) 25%,transparent)',
      '--send-hover-shadow': '0 0 24px color-mix(in srgb,var(--accent) 45%,transparent)',
      '--tool-running-bg': 'var(--accent-bg)',
      '--tool-running-border': 'var(--accent-bg-strong)',
      '--link-hover-glow': '0 0 8px rgba(0,221,255,.4)',
      '--scrollbar-thumb': 'color-mix(in srgb,var(--accent) 18%,transparent)',
      '--scrollbar-thumb-hover': 'color-mix(in srgb,var(--accent) 30%,transparent)',
    },
  },
  {
    key: 'neon-paint',
    name: 'Neon Paint',
    colors: ['#FF2D95','#00E5FF','#FFB800'],
    tokens: {
      '--bg': '#F5F0FF',
      '--sidebar': '#EDE6F8',
      '--border': '#D4C8EE',
      '--border2': 'rgba(0,0,0,0.12)',
      '--text': '#1A1028',
      '--muted': '#6E5A88',
      '--accent': '#FF2D95',
      '--blue': '#00E5FF',
      '--gold': '#FFB800',
      '--code-bg': '#EDE6F8',
      '--surface': '#FFFFFF',
      '--topbar-bg': 'rgba(245,240,255,.98)',
      '--main-bg': 'rgba(245,240,255,0.5)',
      '--focus-ring': 'rgba(255,45,149,.3)',
      '--focus-glow': 'rgba(255,45,149,.08)',
      '--input-bg': 'rgba(255,45,149,.03)',
      '--hover-bg': 'rgba(255,45,149,.05)',
      '--strong': '#0D0518',
      '--em': '#00E5FF',
      '--code-text': '#D81B60',
      '--code-inline-bg': 'rgba(255,45,149,.08)',
      '--pre-text': '#1A1028',
      '--accent-hover': '#E91E80',
      '--accent-bg': 'rgba(255,45,149,0.06)',
      '--accent-bg-strong': 'rgba(255,45,149,0.12)',
      '--accent-text': '#C2185B',
      '--error': '#FF1744',
      '--success': '#00E676',
      '--warning': '#FFB300',
      '--info': '#00E5FF',
      '--radius-sm': '2px',
      '--radius-md': '4px',
      '--radius-card': '4px',
      '--radius-lg': '6px',
      '--font-ui': 'system-ui,-apple-system,sans-serif',
      '--surface-subtle': 'rgba(255,45,149,.025)',
      '--surface-subtle-hover': 'rgba(255,45,149,.05)',
      '--border-subtle': 'rgba(255,45,149,.08)',
      '--border-muted': 'rgba(255,45,149,.12)',
      '--purple': '#FF2D95',
    },
    dark: {
      '--bg': '#0D0A16',
      '--sidebar': '#0A0712',
      '--border': '#2a1f40',
      '--border2': 'rgba(255,45,149,0.15)',
      '--text': '#f0e8ff',
      '--muted': '#9a8ab8',
      '--accent': '#FF2D95',
      '--blue': '#00E5FF',
      '--gold': '#FFB800',
      '--code-bg': '#080510',
      '--surface': '#12101e',
      '--topbar-bg': 'rgba(13,10,22,.98)',
      '--main-bg': 'rgba(13,10,22,0.5)',
      '--focus-ring': 'rgba(255,45,149,.4)',
      '--focus-glow': 'rgba(255,45,149,.12)',
      '--input-bg': 'rgba(255,45,149,.04)',
      '--hover-bg': 'rgba(255,45,149,.06)',
      '--strong': '#fff5ff',
      '--em': '#00E5FF',
      '--code-text': '#f0c0e8',
      '--code-inline-bg': 'rgba(255,45,149,.12)',
      '--pre-text': '#f0e8ff',
      '--accent-hover': '#FF59A8',
      '--accent-bg': 'rgba(255,45,149,0.10)',
      '--accent-bg-strong': 'rgba(255,45,149,0.20)',
      '--accent-text': '#FF80BF',
      '--error': '#FF1744',
      '--success': '#00E676',
      '--warning': '#FFB300',
      '--info': '#00E5FF',
      '--surface-subtle': 'rgba(255,45,149,.03)',
      '--surface-subtle-hover': 'rgba(255,45,149,.06)',
      '--border-subtle': 'rgba(255,45,149,.08)',
      '--border-muted': 'rgba(255,45,149,.12)',
      '--purple': '#FF2D95',
      '--selection-bg': 'color-mix(in srgb,var(--accent) 40%,transparent)',
      '--selection-fg': '#fff',
      '--titlebar-border': 'color-mix(in srgb,var(--accent) 25%,transparent)',
      '--sidebar-shadow': 'inset -1px 0 30px color-mix(in srgb,var(--accent) 4%,transparent)',
      '--input-focus-shadow': '0 0 18px color-mix(in srgb,var(--accent) 25%,transparent)',
      '--send-shadow': '0 0 16px color-mix(in srgb,var(--accent) 30%,transparent)',
      '--send-hover-shadow': '0 0 28px color-mix(in srgb,var(--accent) 50%,transparent)',
      '--tool-running-bg': 'var(--accent-bg)',
      '--tool-running-border': 'var(--accent-bg-strong)',
      '--link-hover-glow': '0 0 10px rgba(0,229,255,.5)',
      '--scrollbar-thumb': 'color-mix(in srgb,var(--accent) 20%,transparent)',
      '--scrollbar-thumb-hover': 'color-mix(in srgb,var(--accent) 35%,transparent)',
    },
  },
  {
    key: 'zeus',
    name: 'Zeus',
    colors: ['#FFD700','#FFBF00','#1A1A00'],
    tokens: {

    },
    dark: {
      '--bg': '#0F0F0F',
      '--sidebar': '#111111',
      '--surface': '#181818',
      '--code-bg': '#181818',
      '--topbar-bg': 'rgba(15,15,15,.98)',
      '--main-bg': 'rgba(15,15,15,0.6)',
      '--border': '#2A2A1E',
      '--border2': 'rgba(255,215,0,0.18)',
      '--input-bg': 'rgba(255,255,255,.04)',
      '--hover-bg': 'rgba(255,215,0,.06)',
      '--surface-subtle': 'rgba(255,255,255,.03)',
      '--surface-subtle-hover': 'rgba(255,255,255,.05)',
      '--border-subtle': 'rgba(255,215,0,.08)',
      '--border-muted': 'rgba(255,215,0,.14)',
      '--focus-ring': 'rgba(255,215,0,.4)',
      '--focus-glow': 'rgba(255,215,0,.1)',
      '--sidebar-bg': '#111111',
      '--sidebar-border': 'color-mix(in srgb,var(--accent) 12%,transparent)',
      '--session-active-bg': 'color-mix(in srgb,var(--accent) 10%,transparent)',
      '--session-active-fg': 'var(--accent)',
      '--session-active-rail-width': '2px',
      '--session-active-rail-color': 'var(--accent)',
      '--session-hover-bg': 'color-mix(in srgb,var(--accent) 5%,transparent)',
      '--composer-bg': '#141414',
      '--composer-border-color': 'color-mix(in srgb,var(--accent) 20%,transparent)',
      '--assistant-msg-bg': '#181818',
      '--user-msg-bg': '#1C1600', '--user-msg-weight': '400', '--user-msg-size': 'var(--message-body-font-size)', '--user-msg-padding': '8px 12px', '--user-msg-radius': '12px',
      '--user-msg-rail': 'color-mix(in srgb,var(--accent) 25%,transparent)',
    },
  },
  {
    key: 'verdigris',
    name: 'Verdigris',
    colors: ['#C89A5A','#0F1714','#22342C'],
    tokens: {

    },
    dark: {
      '--bg': '#0F1714',
      '--sidebar': '#121D18',
      '--border': '#22342C',
      '--border2': 'rgba(200,154,90,0.10)',
      '--text': '#F3ECDD',
      '--muted': '#A8B4A5',
      '--accent': '#C89A5A',
      '--blue': '#C89A5A',
      '--gold': '#C89A5A',
      '--code-bg': '#111B17',
      '--surface': '#16211C',
      '--topbar-bg': 'rgba(15,23,20,.98)',
      '--main-bg': 'rgba(22,33,28,.55)',
      '--focus-ring': 'rgba(200,154,90,.30)',
      '--focus-glow': 'rgba(200,154,90,.10)',
      '--input-bg': 'rgba(255,255,255,.025)',
      '--hover-bg': 'rgba(255,255,255,.045)',
      '--strong': '#FFF8EB',
      '--em': '#D8C5AA',
      '--code-text': '#D6AE74',
      '--code-inline-bg': 'rgba(200,154,90,.08)',
      '--pre-text': '#F3ECDD',
      '--accent-hover': '#D6AE74',
      '--accent-bg': 'rgba(200,154,90,.08)',
      '--accent-bg-strong': 'rgba(200,154,90,.14)',
      '--accent-text': '#E4C28D',
      '--error': '#D26A6A',
      '--success': '#719A68',
      '--warning': '#D1A45C',
      '--info': '#C89A5A',
      '--radius-sm': '1px',
      '--radius-md': '2px',
      '--radius-card': '2px',
      '--radius-lg': '4px',
      '--surface-subtle': 'rgba(255,255,255,.02)',
      '--surface-subtle-hover': 'rgba(255,255,255,.04)',
      '--border-subtle': 'rgba(255,255,255,.06)',
      '--border-muted': 'rgba(255,255,255,.10)',
      '--tool-running-bg': 'var(--accent-bg)',
      '--tool-running-border': 'var(--accent-bg-strong)',
      '--scrollbar-thumb': 'color-mix(in srgb,var(--accent) 20%,transparent)',
      '--scrollbar-thumb-hover': 'color-mix(in srgb,var(--accent) 35%,transparent)',
    },
  },

] as const satisfies readonly SkinSpec[]

export type SkinKey = (typeof SKINS)[number]['key']
export const SKIN_KEYS = SKINS.map((s) => s.key) as [SkinKey, ...SkinKey[]]
export const skinByKey = (key: string): SkinSpec | undefined => SKINS.find((s) => s.key === key)

const block = (selector: string, tokens: TokenMap): string => {
  const entries = Object.entries(tokens)
  return entries.length ? `${selector}{${entries.map(([k, v]) => `${k}:${v}`).join(';')}}\n` : ''
}

/** The token stylesheet: base values, dark overrides, then every skin in declaration order. */
export function renderThemeCss(base: { tokens: TokenMap; dark: TokenMap } = BASE, skins: readonly SkinSpec[] = SKINS): string {
  let css = block(':root', base.tokens) + block(':root.dark', base.dark)
  for (const s of skins) {
    const sel = s.key === 'default' ? ':root:not([data-skin]),:root[data-skin="default"]' : `:root[data-skin="${s.key}"]`
    const darkSel = s.key === 'default' ? ':root.dark:not([data-skin]),:root.dark[data-skin="default"]' : `:root.dark[data-skin="${s.key}"]`
    css += block(sel, s.tokens) + block(darkSel, s.dark)
  }
  return css
}
